# Skip helper for tests that need to fit a brms model. Gated behind an
# environment variable so default `test_dir()` runs without spinning up
# Stan compilers.

skip_unless_brms <- function() {
  if (!identical(Sys.getenv("RUN_BRMS_TESTS"), "true")) {
    testthat::skip("Set RUN_BRMS_TESTS=true to enable brms integration tests.")
  }
  if (!requireNamespace("cmdstanr", quietly = TRUE)) {
    testthat::skip("cmdstanr not available.")
  }
}

# Build (or load from cache) the small fixture fit used by integration tests.
# The fixture lives at tests/testthat/fixtures/sim_fit_small.rds and is
# generated by fitting a tiny model on simulate_tdt() output.
load_fixture_workflow <- function() {
  fixture_dir <- here::here("tests", "testthat", "fixtures")
  dir.create(fixture_dir, showWarnings = FALSE, recursive = TRUE)
  fit_path  <- file.path(fixture_dir, "sim_fit_small")  # brms appends .rds

  raw <- simulate_tdt(seed = 20260512)
  std <- standardize_data(raw,
                          temp = "T", duration = "t_hours",
                          n_total = "n_trials", n_surv = "y_alive",
                          duration_unit = "hours")

  fit_4pl(std,
          chains  = 2, iter = 1500, warmup = 750, cores = 2, seed = 1,
          control = list(adapt_delta = 0.95, max_treedepth = 12),
          file    = fit_path,
          refresh = 0)
}

# Direct CTmax/z fixture: the SAME simulate_tdt() data and design as
# load_fixture_workflow(), but fit with the direct parameterisation
# (ctmax = ~ 1, z = ~ 1, pooled single-group). Used to check that the direct
# helpers recover the planted z/CTmax and agree with the midpoint fixture.
# Cached at tests/testthat/fixtures/sim_fit_direct_small.rds.
load_fixture_workflow_direct <- function() {
  fixture_dir <- here::here("tests", "testthat", "fixtures")
  dir.create(fixture_dir, showWarnings = FALSE, recursive = TRUE)
  fit_path  <- file.path(fixture_dir, "sim_fit_direct_small")  # brms appends .rds

  raw <- simulate_tdt(seed = 20260512)
  std <- standardize_data(raw,
                          temp = "T", duration = "t_hours",
                          n_total = "n_trials", n_surv = "y_alive",
                          duration_unit = "hours")

  fit_4pl(std,
          ctmax   = ~ 1, z = ~ 1,
          chains  = 2, iter = 1500, warmup = 750, cores = 2, seed = 1,
          control = list(adapt_delta = 0.95, max_treedepth = 12),
          file    = fit_path,
          refresh = 0)
}

# Grouped direct fixture: a 2-group simulate_tdt_2group() fit with CTmax/z varying
# by `grp` (ctmax/z ~ 0 + grp, cell-means). Exercises the group-aware extraction
# (per-group z/CTmax via the posterior_linpred engine) against known per-group
# truth. Cached at tests/testthat/fixtures/sim_fit_grouped_small.rds.
load_fixture_workflow_grouped <- function() {
  fixture_dir <- here::here("tests", "testthat", "fixtures")
  dir.create(fixture_dir, showWarnings = FALSE, recursive = TRUE)
  fit_path  <- file.path(fixture_dir, "sim_fit_grouped_small")  # brms appends .rds

  raw <- simulate_tdt_2group(seed = 20260622)
  std <- standardize_data(raw, temp = "T", duration = "t_hours",
                          n_total = "n_trials", n_surv = "y_alive",
                          duration_unit = "hours")
  wf <- fit_4pl(std, ctmax = ~ 0 + grp, z = ~ 0 + grp,
                chains = 2, iter = 1200, warmup = 600, cores = 2, seed = 1,
                control = list(adapt_delta = 0.95, max_treedepth = 12),
                file = fit_path, refresh = 0)
  attr(wf, "truth_2group") <- attr(raw, "truth_2group")
  wf
}

# Beta (continuous-proportion) fixture: standardize_data(proportion =) ->
# fit_4pl(family = Beta(link = "identity")). Cached at
# tests/testthat/fixtures/sim_fit_beta_small.rds.
load_fixture_workflow_beta <- function() {
  fixture_dir <- here::here("tests", "testthat", "fixtures")
  dir.create(fixture_dir, showWarnings = FALSE, recursive = TRUE)
  fit_path  <- file.path(fixture_dir, "sim_fit_beta_small")  # brms appends .rds

  raw <- simulate_tdt_beta(seed = 20260521)
  std <- standardize_data(raw,
                          temp = "T", duration = "t_hours",
                          proportion = "y_prop", duration_unit = "hours")

  fit_4pl(std,
          chains  = 2, iter = 1500, warmup = 750, cores = 2, seed = 1,
          control = list(adapt_delta = 0.95, max_treedepth = 12),
          file    = fit_path,
          refresh = 0)
}
