# Skip helper for tests that need to fit a brms model. Gated behind an
# environment variable so default `test_dir()` runs without spinning up
# Stan compilers.

skip_unless_brms <- function() {
  if (!identical(Sys.getenv("RUN_BRMS_TESTS"), "true")) {
    testthat::skip("Set RUN_BRMS_TESTS=true to enable brms integration tests.")
  }
  if (!requireNamespace("cmdstanr", quietly = TRUE)) {
    testthat::skip("cmdstanr not available.")
  }
}

# Build (or load from cache) the small fixture fit used by integration tests.
# The fixture lives at tests/testthat/fixtures/sim_fit_small.rds and is
# generated by fitting a tiny model on simulate_tdt() output.
load_fixture_workflow <- function() {
  fixture_dir <- here::here("tests", "testthat", "fixtures")
  dir.create(fixture_dir, showWarnings = FALSE, recursive = TRUE)
  fit_path  <- file.path(fixture_dir, "sim_fit_small")  # brms appends .rds

  raw <- simulate_tdt(seed = 20260512)
  std <- standardize_data(raw,
                          temp = "T", duration = "t_hours",
                          n_total = "n_trials", n_surv = "y_alive",
                          duration_unit = "hours")

  fit_4pl(std,
          chains  = 2, iter = 1500, warmup = 750, cores = 2, seed = 1,
          control = list(adapt_delta = 0.95, max_treedepth = 12),
          file    = fit_path,
          refresh = 0)
}

# Beta (continuous-proportion) fixture: standardize_data(proportion =) ->
# fit_4pl(family = Beta(link = "identity")). Cached at
# tests/testthat/fixtures/sim_fit_beta_small.rds.
load_fixture_workflow_beta <- function() {
  fixture_dir <- here::here("tests", "testthat", "fixtures")
  dir.create(fixture_dir, showWarnings = FALSE, recursive = TRUE)
  fit_path  <- file.path(fixture_dir, "sim_fit_beta_small")  # brms appends .rds

  raw <- simulate_tdt_beta(seed = 20260521)
  std <- standardize_data(raw,
                          temp = "T", duration = "t_hours",
                          proportion = "y_prop", duration_unit = "hours")

  fit_4pl(std,
          chains  = 2, iter = 1500, warmup = 750, cores = 2, seed = 1,
          control = list(adapt_delta = 0.95, max_treedepth = 12),
          file    = fit_path,
          refresh = 0)
}
