# Skip helper for tests that need to fit a brms model. Gated behind an
# environment variable so default `test_dir()` runs without spinning up
# Stan compilers.

skip_unless_brms <- function() {
  if (!identical(Sys.getenv("RUN_BRMS_TESTS"), "true")) {
    testthat::skip("Set RUN_BRMS_TESTS=true to enable brms integration tests.")
  }
  if (!requireNamespace("cmdstanr", quietly = TRUE)) {
    testthat::skip("cmdstanr not available.")
  }
}

# Build (or load from cache) the small fixture fit used by integration tests.
# The fixture lives at tests/testthat/fixtures/sim_fit_small.rds and is
# generated by fitting a tiny model on simulate_tdt() output.
load_fixture_workflow <- function() {
  fixture_dir <- here::here("tests", "testthat", "fixtures")
  dir.create(fixture_dir, showWarnings = FALSE, recursive = TRUE)
  fit_path  <- file.path(fixture_dir, "sim_fit_small")  # brms appends .rds

  raw <- simulate_tdt(seed = 20260512)
  std <- standardize_data(raw,
                          temp = "T", duration = "t_hours",
                          n_total = "n_trials", n_surv = "y_alive",
                          duration_unit = "hours")

  fit_4pl(std,
          chains  = 2, iter = 1500, warmup = 750, cores = 2, seed = 1,
          control = list(adapt_delta = 0.95, max_treedepth = 12),
          file    = fit_path,
          refresh = 0)
}

# Direct CTmax/z fixture: the SAME simulate_tdt() data and design as
# load_fixture_workflow(), but fit with the direct parameterisation
# (ctmax = ~ 1, z = ~ 1, pooled single-group). Used to check that the direct
# helpers recover the planted z/CTmax and agree with the midpoint fixture.
# Cached at tests/testthat/fixtures/sim_fit_direct_small.rds.
load_fixture_workflow_direct <- function() {
  fixture_dir <- here::here("tests", "testthat", "fixtures")
  dir.create(fixture_dir, showWarnings = FALSE, recursive = TRUE)
  fit_path  <- file.path(fixture_dir, "sim_fit_direct_small")  # brms appends .rds

  raw <- simulate_tdt(seed = 20260512)
  std <- standardize_data(raw,
                          temp = "T", duration = "t_hours",
                          n_total = "n_trials", n_surv = "y_alive",
                          duration_unit = "hours")

  fit_4pl(std,
          ctmax   = ~ 1, z = ~ 1,
          chains  = 2, iter = 1500, warmup = 750, cores = 2, seed = 1,
          control = list(adapt_delta = 0.95, max_treedepth = 12),
          file    = fit_path,
          refresh = 0)
}

# Grouped direct fixture: a 2-group simulate_tdt_2group() fit with CTmax/z varying
# by `grp` (ctmax/z ~ 0 + grp, cell-means). Exercises the group-aware extraction
# (per-group z/CTmax via the posterior_linpred engine) against known per-group
# truth. Cached at tests/testthat/fixtures/sim_fit_grouped_small.rds.
load_fixture_workflow_grouped <- function() {
  fixture_dir <- here::here("tests", "testthat", "fixtures")
  dir.create(fixture_dir, showWarnings = FALSE, recursive = TRUE)
  fit_path  <- file.path(fixture_dir, "sim_fit_grouped_small")  # brms appends .rds

  raw <- simulate_tdt_2group(seed = 20260622)
  std <- standardize_data(raw, temp = "T", duration = "t_hours",
                          n_total = "n_trials", n_surv = "y_alive",
                          duration_unit = "hours")
  wf <- fit_4pl(std, ctmax = ~ 0 + grp, z = ~ 0 + grp,
                chains = 2, iter = 1200, warmup = 600, cores = 2, seed = 1,
                control = list(adapt_delta = 0.95, max_treedepth = 12),
                file = fit_path, refresh = 0)
  attr(wf, "truth_2group") <- attr(raw, "truth_2group")
  wf
}

# Strongly-bent-curve fixture: the supplement's @sec-joint-extend DGP -- `up`
# declining and `k` rising with temperature, so the absolute-threshold
# log10(LT) curve is genuinely bent (local z varies with T). Reconstructed from
# the cached fit in output/models/ (gitignored -> present locally / where the
# supplement was rendered, skipped in CI). Because file_refit = "never" loads the
# cached posterior, the regenerated response values do not matter -- only the
# deterministic temperature grid (temp_mean = 34) and metadata. Used to guard
# tls() == extract_tdt() parity on the non-linear (inversion / local-z) path.
load_bent_workflow <- function() {
  fit_stub <- file.path(here::here("output", "models"),
                        "sim_4pl_ext_betabin_DEFAULT_strong_v1")
  if (!file.exists(paste0(fit_stub, ".rds")))
    testthat::skip(paste0("bent-curve fit (", fit_stub,
                          ".rds) absent; local-only (gitignored), skipped in CI."))
  temps <- c(30, 32, 34, 36, 38); durations <- c(1, 5, 15, 45, 135, 405)
  tp <- list(ell_raw = qlogis(0.05 / 0.49), up_raw_0 = qlogis((0.92 - 0.51) / 0.49),
             up_raw_T = -0.60, log_k_0 = log(8), log_k_T = 0.30,
             m_beta0 = 1.5, m_beta1 = -0.15, T_bar = 34)
  set.seed(1)
  d  <- expand.grid(T = temps, t = durations, rep = seq_len(30))
  Tc <- d$T - tp$T_bar
  ell <- 0.49 * plogis(tp$ell_raw)
  up  <- 0.51 + 0.49 * plogis(tp$up_raw_0 + tp$up_raw_T * Tc)
  k   <- exp(tp$log_k_0 + tp$log_k_T * Tc)
  mid <- tp$m_beta0 + tp$m_beta1 * Tc
  p   <- ell + (up - ell) / (1 + exp(k * (log10(d$t) - mid)))
  d$n <- 30
  d$y <- rbinom(nrow(d), 30, rbeta(nrow(d), p * 5, (1 - p) * 5))
  std <- standardize_data(d, temp = "T", duration = "t", n_total = "n",
                          n_surv = "y", duration_unit = "minutes")
  suppressMessages(fit_4pl(std, chains = 4, iter = 2000, cores = 4, seed = 123,
                           file = fit_stub, file_refit = "never"))
}

# Beta (continuous-proportion) fixture: standardize_data(proportion =) ->
# fit_4pl(family = Beta(link = "identity")). Cached at
# tests/testthat/fixtures/sim_fit_beta_small.rds.
load_fixture_workflow_beta <- function() {
  fixture_dir <- here::here("tests", "testthat", "fixtures")
  dir.create(fixture_dir, showWarnings = FALSE, recursive = TRUE)
  fit_path  <- file.path(fixture_dir, "sim_fit_beta_small")  # brms appends .rds

  raw <- simulate_tdt_beta(seed = 20260521)
  std <- standardize_data(raw,
                          temp = "T", duration = "t_hours",
                          proportion = "y_prop", duration_unit = "hours")

  fit_4pl(std,
          chains  = 2, iter = 1500, warmup = 750, cores = 2, seed = 1,
          control = list(adapt_delta = 0.95, max_treedepth = 12),
          file    = fit_path,
          refresh = 0)
}
