<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.32">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Daniel Noble (with Claude assistance)">
<meta name="dcterms.date" content="2026-05-16">

<title>Joint Bayesian 4PL vs two-stage TDT estimators — bias, coverage, and sensitivity</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="2026-05-16-two-stage-bias-sim-writeup_files/libs/clipboard/clipboard.min.js"></script>
<script src="2026-05-16-two-stage-bias-sim-writeup_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="2026-05-16-two-stage-bias-sim-writeup_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="2026-05-16-two-stage-bias-sim-writeup_files/libs/quarto-html/popper.min.js"></script>
<script src="2026-05-16-two-stage-bias-sim-writeup_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="2026-05-16-two-stage-bias-sim-writeup_files/libs/quarto-html/anchor.min.js"></script>
<link href="2026-05-16-two-stage-bias-sim-writeup_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="2026-05-16-two-stage-bias-sim-writeup_files/libs/quarto-html/quarto-syntax-highlighting-37eea08aefeeee20ff55810ff984fec1.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="2026-05-16-two-stage-bias-sim-writeup_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="2026-05-16-two-stage-bias-sim-writeup_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="2026-05-16-two-stage-bias-sim-writeup_files/libs/bootstrap/bootstrap-81267100e462c21b3d6c0d5bf76a3417.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#aim" id="toc-aim" class="nav-link active" data-scroll-target="#aim"><span class="header-section-number">1</span> Aim</a></li>
  <li><a href="#common-methods" id="toc-common-methods" class="nav-link" data-scroll-target="#common-methods"><span class="header-section-number">2</span> Common methods</a></li>
  <li><a href="#scenario-1-strict-equivalence-baseline" id="toc-scenario-1-strict-equivalence-baseline" class="nav-link" data-scroll-target="#scenario-1-strict-equivalence-baseline"><span class="header-section-number">3</span> Scenario 1 — Strict equivalence baseline</a></li>
  <li><a href="#scenario-2-likelihood-misspecification-only" id="toc-scenario-2-likelihood-misspecification-only" class="nav-link" data-scroll-target="#scenario-2-likelihood-misspecification-only"><span class="header-section-number">4</span> Scenario 2 — Likelihood misspecification only</a></li>
  <li><a href="#scenario-3-heat-lowers-max-survival-asymmetric-u-drift" id="toc-scenario-3-heat-lowers-max-survival-asymmetric-u-drift" class="nav-link" data-scroll-target="#scenario-3-heat-lowers-max-survival-asymmetric-u-drift"><span class="header-section-number">5</span> Scenario 3 — Heat lowers max survival (asymmetric u drift)</a></li>
  <li><a href="#scenario-4-asymptotes-compress-symmetric-drift" id="toc-scenario-4-asymptotes-compress-symmetric-drift" class="nav-link" data-scroll-target="#scenario-4-asymptotes-compress-symmetric-drift"><span class="header-section-number">6</span> Scenario 4 — Asymptotes compress (symmetric drift)</a></li>
  <li><a href="#scenario-5-heat-sharpens-curve-varying-k" id="toc-scenario-5-heat-sharpens-curve-varying-k" class="nav-link" data-scroll-target="#scenario-5-heat-sharpens-curve-varying-k"><span class="header-section-number">7</span> Scenario 5 — Heat sharpens curve (varying k)</a></li>
  <li><a href="#scenario-6-sweep-strength-of-u-drift" id="toc-scenario-6-sweep-strength-of-u-drift" class="nav-link" data-scroll-target="#scenario-6-sweep-strength-of-u-drift"><span class="header-section-number">8</span> Scenario 6 — Sweep: strength of u drift</a></li>
  <li><a href="#scenario-7-sweep-level-of-upper-asymptote" id="toc-scenario-7-sweep-level-of-upper-asymptote" class="nav-link" data-scroll-target="#scenario-7-sweep-level-of-upper-asymptote"><span class="header-section-number">9</span> Scenario 7 — Sweep: level of upper asymptote</a></li>
  <li><a href="#scenario-8-sweep-design-intensity" id="toc-scenario-8-sweep-design-intensity" class="nav-link" data-scroll-target="#scenario-8-sweep-design-intensity"><span class="header-section-number">10</span> Scenario 8 — Sweep: design intensity</a></li>
  <li><a href="#cross-cutting-summary" id="toc-cross-cutting-summary" class="nav-link" data-scroll-target="#cross-cutting-summary"><span class="header-section-number">11</span> Cross-cutting summary</a></li>
  <li><a href="#joint-4pl-convergence-across-scenarios" id="toc-joint-4pl-convergence-across-scenarios" class="nav-link" data-scroll-target="#joint-4pl-convergence-across-scenarios"><span class="header-section-number">12</span> Joint 4PL convergence across scenarios</a></li>
  <li><a href="#open-issues" id="toc-open-issues" class="nav-link" data-scroll-target="#open-issues"><span class="header-section-number">13</span> Open issues</a></li>
  <li><a href="#bottom-line" id="toc-bottom-line" class="nav-link" data-scroll-target="#bottom-line"><span class="header-section-number">14</span> Bottom line</a></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Joint Bayesian 4PL vs two-stage TDT estimators — bias, coverage, and sensitivity</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Daniel Noble (with Claude assistance) </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">May 16, 2026</p>
    </div>
  </div>
  
    <div>
    <div class="quarto-title-meta-heading">Modified</div>
    <div class="quarto-title-meta-contents">
      <p class="date-modified">May 19, 2026</p>
    </div>
  </div>
    
  </div>
  


</header>


<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>This note supersedes <a href="2026-05-14-two-stage-bias-sim-results.html"><code>2026-05-14-two-stage-bias-sim-results.qmd</code></a> and <a href="2026-05-15-sensitivity-sweeps.html"><code>2026-05-15-sensitivity-sweeps.qmd</code></a>.</p>
<p><strong>2026-05-19 rebuild.</strong> All 25 cells re-run with new sampler settings (3 chains × 3000 iter, warmup 1500, <code>max_treedepth = 16</code>) and <span class="math inline">\(N_{\text{sim}} = 1000\)</span> across every scenario (the original sensitivity sweeps used 500). Each fit now reports <strong>six</strong> estimators per dataset: joint 4PL with <code>target_surv = "relative"</code> and <code>target_surv = "absolute"</code>, each two-stage variant (binomial / beta-binomial Stage 1) with both Normal-quantile and t-quantile Stage-2 delta-method CIs. Methods are documented in <a href="2026-05-13-two-stage-bias-sim-methods.qmd"><code>2026-05-13-two-stage-bias-sim-methods.qmd</code></a>; this note refers back rather than restating.</p>
</div>
</div>
<section id="aim" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Aim</h1>
<p>The thermal-death-time (TDT) framework is overwhelmingly fitted with a two-stage pipeline: per-temperature binomial GLMs estimate <span class="math inline">\(\log_{10}\text{LT}_{50}\)</span>, then those five (or so) point estimates are regressed against temperature with unweighted OLS to extract the classical quantities <span class="math inline">\(z\)</span> and <span class="math inline">\(CT_{\max,1\text{h}}\)</span>. We want to know when this pipeline gives the correct answer with the correct uncertainty, and when it does not.</p>
<p>The joint Bayesian 4PL fits the full dose-response surface in one go. Algebraically it returns the same <span class="math inline">\(z\)</span> and <span class="math inline">\(CT_{\max,1\text{h}}\)</span> when the strict-equivalence assumptions hold (constant asymptotes near 0/1, no overdispersion, common slope across temperature). When those assumptions break — partial asymptotes, drifting upper bound, overdispersed counts, sparse design — there is no algebraic guarantee that the two are the same, and the two-stage’s estimating equations have no parameter to absorb the missing structure.</p>
<p>The simulation study compares six estimators side-by-side over eight controlled scenarios (25 cells, 25,000 simulated datasets). Two estimators isolate the joint-4PL’s <em>threshold definition</em> (relative vs absolute) on the same fit; four isolate the two-stage’s <em>likelihood</em> (binomial vs beta-binomial Stage 1) and <em>small-sample CI correction</em> (Normal vs t-quantile delta-method Stage 2). The aim is not to advocate for the joint 4PL on principle, but to map where the two-stage’s deficit becomes operationally important — and where it does not.</p>
</section>
<section id="common-methods" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Common methods</h1>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p>Full details, including the analytical truth construction, the parameter feasibility check that runs before any compute starts, and the diagnostic-criterion table, are in <a href="2026-05-13-two-stage-bias-sim-methods.qmd"><code>2026-05-13-two-stage-bias-sim-methods.qmd</code></a>. This section gives only the headline numbers needed to read the results.</p>
</div>
</div>
<p><strong>Six estimators per dataset.</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Label</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>joint_4pl</code></td>
<td><code>bayesTLS::extract_tdt(target_surv = "relative")</code>: <span class="math inline">\(z\)</span> and <span class="math inline">\(CT_{\max,1\text{h}}\)</span> extracted from the posterior at the asymptote midpoint <span class="math inline">\(p = (\text{low}+\text{up})/2\)</span> (the package default).</td>
</tr>
<tr class="even">
<td><code>joint_4pl_abs</code></td>
<td>Same fit, <code>target_surv = "absolute"</code>: extraction at <span class="math inline">\(p = 0.5\)</span> literal. Matches the analytical truth function’s definition.</td>
</tr>
<tr class="odd">
<td><code>two_stage_bin</code></td>
<td>Field default: per-temperature binomial GLM Stage 1, unweighted Stage-2 OLS, Normal-quantile delta-method CIs (<span class="math inline">\(z_{0.975} = 1.96\)</span>).</td>
</tr>
<tr class="even">
<td><code>two_stage_bin_t</code></td>
<td>Same point estimate as <code>two_stage_bin</code>; Stage-2 CIs use t-quantile delta-method (<span class="math inline">\(t_{0.975, n_T-2}\)</span> — 3.18 at full design, 12.71 at sparse). Small-sample correction.</td>
</tr>
<tr class="odd">
<td><code>two_stage_bb</code></td>
<td>“Patched” two-stage: per-T beta-binomial GLMM Stage 1 via <code>glmmTMB</code>, unweighted Stage-2 OLS, Normal-quantile CIs. Isolates the <em>likelihood</em> contribution of the field-default deficit.</td>
</tr>
<tr class="even">
<td><code>two_stage_bb_t</code></td>
<td>Same as <code>two_stage_bb</code> but with t-quantile Stage-2 CIs.</td>
</tr>
</tbody>
</table>
<p>The joint 4PL is a <code>brms</code>-fit non-linear <code>beta_binomial(link = "identity")</code> model in which all four 4PL sub-parameters carry a centred-temperature slope. Both joint extracts come from one fit (no extra compute).</p>
<p><strong>Design grid.</strong> Five assay temperatures (30, 32, 34, 36, 38 °C) × six exposure durations (1, 5, 15, 45, 135, 405 minutes) = 30 cells per dataset. Each cell is replicated by <span class="math inline">\(n_{\text{reps}}\)</span> independent cups, each with <span class="math inline">\(N \sim \text{Uniform}\{10, \dots, 20\}\)</span> individuals. A Scenario-1 dataset with <span class="math inline">\(n_{\text{reps}}=5\)</span> is therefore 150 cups totalling roughly 2,000 individuals. Scenario 8 explicitly varies the grid (sparse 3 T × 4 durations = 12 cells per dataset).</p>
<p><strong>Two truths, one per CTmax/z definition.</strong> Five of the six estimators target the <em>absolute</em>-50% population quantity (joint_4pl_abs, two_stage_bin/_t, two_stage_bb/_t) and are compared against the absolute truth from <code>compute_ols_truth()</code>: <span class="math inline">\(\log_{10}\text{LT}_{50}^{\text{abs}}(T)
= \text{mid}(T) + \frac{1}{k(T)}\ln\frac{u(T)-0.5}{0.5-\ell(T)}\)</span> evaluated at every design temperature and OLS-projected. The sixth, <code>joint_4pl</code> (the relative extract), targets the <em>relative</em> quantity — temperature where <span class="math inline">\(\text{mid}(T) = \log_{10}60\)</span> — and is compared against a <strong>separate truth</strong> that uses the mid line directly, no asymmetry correction. In this study <code>mid(T) = 1.5 + (-0.15)(T - 34)</code> in every cell (no scenario varies the mid line), so the relative truth is the same constant across all 25 cells: <span class="math inline">\(z_{\text{true}}^{\text{rel}} = 6.667\)</span> °C and <span class="math inline">\(CT_{\max,1\text{h}}^{\text{rel}} = 32.147\)</span> °C. <strong>Without this two-truth substitution, the joint_4pl rows would carry a labelling offset against the absolute truth wherever the asymptotes deviate from 0/1 — that offset was the original open issue 1 from the 2026-05-16 first pass and is what the rewrite resolves.</strong></p>
<p><strong>Sample sizes.</strong> <span class="math inline">\(N_{\text{sim}} = 1000\)</span> datasets per cell across <strong>every</strong> scenario in this rebuild (the 2026-05-16 first pass used 500 for Scen 6–8; standardised to 1000 in the 2026-05-19 re-run). Cells are pre-flighted before any compute starts, including a cross-cell distinctness check on data hashes that catches CLI plumbing bugs.</p>
<p><strong>Performance metrics.</strong> For each estimator and each output quantity (<span class="math inline">\(z\)</span>, <span class="math inline">\(CT_{\max,1\text{h}}\)</span>): mean signed bias and its Monte-Carlo SE, RMSE, empirical 95% coverage and its MC SE (binomial proportion), and median 95% CI width. All computed across the per-simulation rows in the cell.</p>
<p><strong>BB Stage-1 pathology screening.</strong> The driver’s success check (finite coefficients, negative slope) lets through a small fraction of beta-binomial Stage-1 fits whose Hessian is numerically rank-deficient — these pass as “successful” but produce wildly biased Stage-2 estimates (z bias up to 849 °C; CTmax bias up to 433 °C). Across all 25,000 sims, 153 (0.6 %) match this pattern, concentrated in Scenario 1 (boundary asymptotes) and the Scenario 8 sparse cells. <strong>Sims where the two-stage BB estimate has |z bias| &gt; 20 °C OR |CTmax bias| &gt; 10 °C are dropped from the <code>two_stage_bb</code> and <code>two_stage_bb_t</code> rows</strong>, but retained for the four non-BB methods. The cut-offs are well above the largest legitimate two-stage failure observed anywhere in the study (Scenario 7 <span class="math inline">\(u_0 = 0.65\)</span>, BB CTmax bias = −6.3 °C). All summaries reported below use the screened per-sim data.</p>
<p><strong>Diagnostics.</strong> Joint 4PL chains: <strong>3 chains × 3000 iterations (warmup 1500, post-warmup 4500), <code>adapt_delta = 0.95</code>, <code>max_treedepth = 16</code></strong>. R̂ &lt; 1.01, ESS &gt; 400, zero divergent transitions, BFMI &gt; 0.3. Per-cell pass rates are reported alongside the bias / coverage tables. The new sampler settings are an upgrade from the 2 chains × 2000 / <code>max_treedepth = 12</code> used in the earlier pass.</p>
</section>
<section id="scenario-1-strict-equivalence-baseline" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Scenario 1 — Strict equivalence baseline</h1>
<p><strong>Question.</strong> When all strict-equivalence assumptions hold (asymptotes pinned at 0 and 1, no overdispersion, single slope across temperature), do the three estimators agree, and is each calibrated? This is the floor scenario — divergence here would signal a bug.</p>
<p><strong>Prediction.</strong> All three estimators are correctly specified for this DGP (the joint 4PL’s beta-binomial likelihood collapses to binomial as <span class="math inline">\(\phi \to \infty\)</span>). Bias should be within MC SE and coverage near 0.95 for all three. We expected the joint 4PL to deliver the narrowest CIs (joint fit pools information across temperature), with the two two-stage variants near-identical (no overdispersion to exploit).</p>
<p><strong>Design.</strong> DGP: <code>low = 0.001</code>, <code>up = 0.999</code>, <code>k = 8</code>, midpoint linear in <span class="math inline">\(T\)</span> with slope <span class="math inline">\(-0.15\)</span>, binomial likelihood. True <span class="math inline">\(z = 6.667\)</span>, true <span class="math inline">\(CT_{\max,1\text{h}} = 32.146\,^\circ\text{C}\)</span>. Two cells: <span class="math inline">\(n_{\text{reps}} \in \{3, 5\}\)</span>. <span class="math inline">\(N_{\text{sim}} = 1000\)</span> per cell.</p>
<div class="cell">
<div class="cell-output-display">
<div class="kable-table">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 19%">
<col style="width: 27%">
<col style="width: 10%">
<col style="width: 5%">
<col style="width: 15%">
<col style="width: 6%">
<col style="width: 9%">
<col style="width: 6%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Cell</th>
<th style="text-align: left;">Method</th>
<th style="text-align: left;">Quantity</th>
<th style="text-align: right;">n_ok</th>
<th style="text-align: left;">Bias</th>
<th style="text-align: left;">RMSE</th>
<th style="text-align: left;">Coverage</th>
<th style="text-align: left;">Width</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">scen1_strict_eq_n3</td>
<td style="text-align: left;">Two-stage bin (Normal CI)</td>
<td style="text-align: left;">z</td>
<td style="text-align: right;">1000</td>
<td style="text-align: left;">+0.013 (0.009)</td>
<td style="text-align: left;">0.281</td>
<td style="text-align: left;">84.3%</td>
<td style="text-align: left;">0.91</td>
</tr>
<tr class="even">
<td style="text-align: left;">scen1_strict_eq_n3</td>
<td style="text-align: left;">Two-stage bin (t CI)</td>
<td style="text-align: left;">z</td>
<td style="text-align: right;">1000</td>
<td style="text-align: left;">+0.013 (0.009)</td>
<td style="text-align: left;">0.281</td>
<td style="text-align: left;">93.7%</td>
<td style="text-align: left;">1.48</td>
</tr>
<tr class="odd">
<td style="text-align: left;">scen1_strict_eq_n3</td>
<td style="text-align: left;">Two-stage BB (Normal CI)</td>
<td style="text-align: left;">z</td>
<td style="text-align: right;">974</td>
<td style="text-align: left;">+0.035 (0.029)</td>
<td style="text-align: left;">0.895</td>
<td style="text-align: left;">84.9%</td>
<td style="text-align: left;">1.00</td>
</tr>
<tr class="even">
<td style="text-align: left;">scen1_strict_eq_n3</td>
<td style="text-align: left;">Two-stage BB (t CI)</td>
<td style="text-align: left;">z</td>
<td style="text-align: right;">974</td>
<td style="text-align: left;">+0.035 (0.029)</td>
<td style="text-align: left;">0.895</td>
<td style="text-align: left;">93.8%</td>
<td style="text-align: left;">1.63</td>
</tr>
<tr class="odd">
<td style="text-align: left;">scen1_strict_eq_n3</td>
<td style="text-align: left;">Joint 4PL (relative)</td>
<td style="text-align: left;">z</td>
<td style="text-align: right;">1000</td>
<td style="text-align: left;">+0.052 (0.009)</td>
<td style="text-align: left;">0.275</td>
<td style="text-align: left;">98.2%</td>
<td style="text-align: left;">1.33</td>
</tr>
<tr class="even">
<td style="text-align: left;">scen1_strict_eq_n3</td>
<td style="text-align: left;">Joint 4PL (absolute)</td>
<td style="text-align: left;">z</td>
<td style="text-align: right;">1000</td>
<td style="text-align: left;">+0.019 (0.009)</td>
<td style="text-align: left;">0.268</td>
<td style="text-align: left;">97.9%</td>
<td style="text-align: left;">1.29</td>
</tr>
<tr class="odd">
<td style="text-align: left;">scen1_strict_eq_n3</td>
<td style="text-align: left;">Two-stage bin (Normal CI)</td>
<td style="text-align: left;">CTmax_1hr</td>
<td style="text-align: right;">1000</td>
<td style="text-align: left;">-0.006 (0.004)</td>
<td style="text-align: left;">0.136</td>
<td style="text-align: left;">85.1%</td>
<td style="text-align: left;">0.46</td>
</tr>
<tr class="even">
<td style="text-align: left;">scen1_strict_eq_n3</td>
<td style="text-align: left;">Two-stage bin (t CI)</td>
<td style="text-align: left;">CTmax_1hr</td>
<td style="text-align: right;">1000</td>
<td style="text-align: left;">-0.006 (0.004)</td>
<td style="text-align: left;">0.136</td>
<td style="text-align: left;">95.2%</td>
<td style="text-align: left;">0.75</td>
</tr>
<tr class="odd">
<td style="text-align: left;">scen1_strict_eq_n3</td>
<td style="text-align: left;">Two-stage BB (Normal CI)</td>
<td style="text-align: left;">CTmax_1hr</td>
<td style="text-align: right;">974</td>
<td style="text-align: left;">-0.007 (0.019)</td>
<td style="text-align: left;">0.592</td>
<td style="text-align: left;">86.2%</td>
<td style="text-align: left;">0.51</td>
</tr>
<tr class="even">
<td style="text-align: left;">scen1_strict_eq_n3</td>
<td style="text-align: left;">Two-stage BB (t CI)</td>
<td style="text-align: left;">CTmax_1hr</td>
<td style="text-align: right;">974</td>
<td style="text-align: left;">-0.007 (0.019)</td>
<td style="text-align: left;">0.592</td>
<td style="text-align: left;">96.1%</td>
<td style="text-align: left;">0.83</td>
</tr>
<tr class="odd">
<td style="text-align: left;">scen1_strict_eq_n3</td>
<td style="text-align: left;">Joint 4PL (relative)</td>
<td style="text-align: left;">CTmax_1hr</td>
<td style="text-align: right;">1000</td>
<td style="text-align: left;">-0.025 (0.004)</td>
<td style="text-align: left;">0.132</td>
<td style="text-align: left;">98.5%</td>
<td style="text-align: left;">0.65</td>
</tr>
<tr class="even">
<td style="text-align: left;">scen1_strict_eq_n3</td>
<td style="text-align: left;">Joint 4PL (absolute)</td>
<td style="text-align: left;">CTmax_1hr</td>
<td style="text-align: right;">1000</td>
<td style="text-align: left;">-0.017 (0.004)</td>
<td style="text-align: left;">0.130</td>
<td style="text-align: left;">98.3%</td>
<td style="text-align: left;">0.64</td>
</tr>
<tr class="odd">
<td style="text-align: left;">scen1_strict_eq_n5</td>
<td style="text-align: left;">Two-stage bin (Normal CI)</td>
<td style="text-align: left;">z</td>
<td style="text-align: right;">1000</td>
<td style="text-align: left;">+0.026 (0.007)</td>
<td style="text-align: left;">0.215</td>
<td style="text-align: left;">83.8%</td>
<td style="text-align: left;">0.72</td>
</tr>
<tr class="even">
<td style="text-align: left;">scen1_strict_eq_n5</td>
<td style="text-align: left;">Two-stage bin (t CI)</td>
<td style="text-align: left;">z</td>
<td style="text-align: right;">1000</td>
<td style="text-align: left;">+0.026 (0.007)</td>
<td style="text-align: left;">0.215</td>
<td style="text-align: left;">93.6%</td>
<td style="text-align: left;">1.18</td>
</tr>
<tr class="odd">
<td style="text-align: left;">scen1_strict_eq_n5</td>
<td style="text-align: left;">Two-stage BB (Normal CI)</td>
<td style="text-align: left;">z</td>
<td style="text-align: right;">975</td>
<td style="text-align: left;">-0.017 (0.028)</td>
<td style="text-align: left;">0.866</td>
<td style="text-align: left;">82.0%</td>
<td style="text-align: left;">0.81</td>
</tr>
<tr class="even">
<td style="text-align: left;">scen1_strict_eq_n5</td>
<td style="text-align: left;">Two-stage BB (t CI)</td>
<td style="text-align: left;">z</td>
<td style="text-align: right;">975</td>
<td style="text-align: left;">-0.017 (0.028)</td>
<td style="text-align: left;">0.866</td>
<td style="text-align: left;">93.2%</td>
<td style="text-align: left;">1.31</td>
</tr>
<tr class="odd">
<td style="text-align: left;">scen1_strict_eq_n5</td>
<td style="text-align: left;">Joint 4PL (relative)</td>
<td style="text-align: left;">z</td>
<td style="text-align: right;">1000</td>
<td style="text-align: left;">+0.045 (0.007)</td>
<td style="text-align: left;">0.219</td>
<td style="text-align: left;">97.1%</td>
<td style="text-align: left;">0.98</td>
</tr>
<tr class="even">
<td style="text-align: left;">scen1_strict_eq_n5</td>
<td style="text-align: left;">Joint 4PL (absolute)</td>
<td style="text-align: left;">z</td>
<td style="text-align: right;">1000</td>
<td style="text-align: left;">+0.021 (0.007)</td>
<td style="text-align: left;">0.214</td>
<td style="text-align: left;">96.7%</td>
<td style="text-align: left;">0.95</td>
</tr>
<tr class="odd">
<td style="text-align: left;">scen1_strict_eq_n5</td>
<td style="text-align: left;">Two-stage bin (Normal CI)</td>
<td style="text-align: left;">CTmax_1hr</td>
<td style="text-align: right;">1000</td>
<td style="text-align: left;">-0.010 (0.003)</td>
<td style="text-align: left;">0.105</td>
<td style="text-align: left;">84.2%</td>
<td style="text-align: left;">0.37</td>
</tr>
<tr class="even">
<td style="text-align: left;">scen1_strict_eq_n5</td>
<td style="text-align: left;">Two-stage bin (t CI)</td>
<td style="text-align: left;">CTmax_1hr</td>
<td style="text-align: right;">1000</td>
<td style="text-align: left;">-0.010 (0.003)</td>
<td style="text-align: left;">0.105</td>
<td style="text-align: left;">94.6%</td>
<td style="text-align: left;">0.59</td>
</tr>
<tr class="odd">
<td style="text-align: left;">scen1_strict_eq_n5</td>
<td style="text-align: left;">Two-stage BB (Normal CI)</td>
<td style="text-align: left;">CTmax_1hr</td>
<td style="text-align: right;">975</td>
<td style="text-align: left;">-0.013 (0.020)</td>
<td style="text-align: left;">0.616</td>
<td style="text-align: left;">85.6%</td>
<td style="text-align: left;">0.41</td>
</tr>
<tr class="even">
<td style="text-align: left;">scen1_strict_eq_n5</td>
<td style="text-align: left;">Two-stage BB (t CI)</td>
<td style="text-align: left;">CTmax_1hr</td>
<td style="text-align: right;">975</td>
<td style="text-align: left;">-0.013 (0.020)</td>
<td style="text-align: left;">0.616</td>
<td style="text-align: left;">94.9%</td>
<td style="text-align: left;">0.67</td>
</tr>
<tr class="odd">
<td style="text-align: left;">scen1_strict_eq_n5</td>
<td style="text-align: left;">Joint 4PL (relative)</td>
<td style="text-align: left;">CTmax_1hr</td>
<td style="text-align: right;">1000</td>
<td style="text-align: left;">-0.023 (0.003)</td>
<td style="text-align: left;">0.104</td>
<td style="text-align: left;">97.8%</td>
<td style="text-align: left;">0.48</td>
</tr>
<tr class="even">
<td style="text-align: left;">scen1_strict_eq_n5</td>
<td style="text-align: left;">Joint 4PL (absolute)</td>
<td style="text-align: left;">CTmax_1hr</td>
<td style="text-align: right;">1000</td>
<td style="text-align: left;">-0.017 (0.003)</td>
<td style="text-align: left;">0.102</td>
<td style="text-align: left;">98.0%</td>
<td style="text-align: left;">0.48</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-scen1" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-scen1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="2026-05-16-two-stage-bias-sim-writeup_files/figure-html/fig-scen1-1.png" class="img-fluid figure-img" width="768">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-scen1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Scenario 1 (strict equivalence baseline). (a) Mean bias with 95% MC-SE intervals; dashed line at zero. (b) Empirical 95% CI coverage with 95% binomial intervals; dashed line at the nominal 0.95. Top row: <span class="math inline">\(n_{reps}=3\)</span>; bottom row: <span class="math inline">\(n_{reps}=5\)</span>. Both quantities (<span class="math inline">\(z\)</span> and <span class="math inline">\(CT_{\max,1h}\)</span>) are within MC SE of zero bias and within MC SE of nominal coverage for all three estimators, as predicted.
</figcaption>
</figure>
</div>
</div>
</div>
<p><strong>Read.</strong> Bias predictions held for all six estimators (signed bias within MC SE of zero on both quantities, both cells). The Normal-CI two-stage estimators <strong>under-cover</strong> at 84–86% on both <span class="math inline">\(z\)</span> and <span class="math inline">\(CT_{\max,1\text{h}}\)</span>, regardless of Stage-1 family — the Stage-2 OLS on five LT50 points propagates less variance than the underlying sampling distribution requires. <strong>The t-quantile correction at <span class="math inline">\(df = n_T - 2 = 3\)</span> closes the gap</strong>: both <code>two_stage_bin_t</code> and <code>two_stage_bb_t</code> now cover at 93–97% on both quantities. This is the clean regime where the small-sample CI fix does the job. Joint 4PL covers at 97–99% on both extracts (slightly over nominal but within MC SE of 0.95); the relative and absolute extracts are within 0.01 °C of each other on CTmax (asymptotes are at the reparam boundary, so the asymmetry correction is essentially zero).</p>
<p>The BB Stage-1 variant produced a small fraction of pathological fits in this scenario (passing the driver’s success check but with nonsensical Stage-2 estimates); those sims are now screened out for the BB methods only — see “BB Stage-1 pathology screening” in the Common methods section. The n_ok counts for <code>two_stage_bb</code> / <code>two_stage_bb_t</code> in the table reflect the post-screen sample size.</p>
</section>
<section id="scenario-2-likelihood-misspecification-only" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Scenario 2 — Likelihood misspecification only</h1>
<p><strong>Question.</strong> With identical curve shape to Scenario 1 but beta-binomial overdispersion (φ = 5) added to the data-generating likelihood, what does the field default lose by ignoring overdispersion?</p>
<p><strong>Prediction.</strong> All three should remain unbiased — the curve shape is unchanged, so the regression’s mean structure is correct under all three estimators. We expected the binomial two-stage to have wider CIs than the patched (beta-binomial) two-stage, but coverage near nominal because Stage-2 OLS reads the residual variance off the <span class="math inline">\(\log_{10}\text{LT}_{50}\)</span> scatter. The patched two-stage should give narrower, calibrated CIs. The joint 4PL — narrowest, calibrated.</p>
<p><strong>Design.</strong> Same shape as Scenario 1 (boundary asymptotes), but DGP likelihood is beta-binomial with φ = 5. Two cells: <span class="math inline">\(n_{\text{reps}} \in \{3, 5\}\)</span>. <span class="math inline">\(N_{\text{sim}} = 1000\)</span> per cell.</p>
<div class="cell">
<div class="cell-output-display">
<div class="kable-table">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 21%">
<col style="width: 26%">
<col style="width: 10%">
<col style="width: 5%">
<col style="width: 15%">
<col style="width: 6%">
<col style="width: 9%">
<col style="width: 6%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Cell</th>
<th style="text-align: left;">Method</th>
<th style="text-align: left;">Quantity</th>
<th style="text-align: right;">n_ok</th>
<th style="text-align: left;">Bias</th>
<th style="text-align: left;">RMSE</th>
<th style="text-align: left;">Coverage</th>
<th style="text-align: left;">Width</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">scen2_lik_misspec_n3</td>
<td style="text-align: left;">Two-stage bin (Normal CI)</td>
<td style="text-align: left;">z</td>
<td style="text-align: right;">1000</td>
<td style="text-align: left;">-0.009 (0.018)</td>
<td style="text-align: left;">0.552</td>
<td style="text-align: left;">84.4%</td>
<td style="text-align: left;">1.81</td>
</tr>
<tr class="even">
<td style="text-align: left;">scen2_lik_misspec_n3</td>
<td style="text-align: left;">Two-stage bin (t CI)</td>
<td style="text-align: left;">z</td>
<td style="text-align: right;">1000</td>
<td style="text-align: left;">-0.009 (0.018)</td>
<td style="text-align: left;">0.552</td>
<td style="text-align: left;">94.6%</td>
<td style="text-align: left;">2.94</td>
</tr>
<tr class="odd">
<td style="text-align: left;">scen2_lik_misspec_n3</td>
<td style="text-align: left;">Two-stage BB (Normal CI)</td>
<td style="text-align: left;">z</td>
<td style="text-align: right;">991</td>
<td style="text-align: left;">-0.004 (0.022)</td>
<td style="text-align: left;">0.686</td>
<td style="text-align: left;">84.9%</td>
<td style="text-align: left;">1.81</td>
</tr>
<tr class="even">
<td style="text-align: left;">scen2_lik_misspec_n3</td>
<td style="text-align: left;">Two-stage BB (t CI)</td>
<td style="text-align: left;">z</td>
<td style="text-align: right;">991</td>
<td style="text-align: left;">-0.004 (0.022)</td>
<td style="text-align: left;">0.686</td>
<td style="text-align: left;">93.4%</td>
<td style="text-align: left;">2.94</td>
</tr>
<tr class="odd">
<td style="text-align: left;">scen2_lik_misspec_n3</td>
<td style="text-align: left;">Joint 4PL (relative)</td>
<td style="text-align: left;">z</td>
<td style="text-align: right;">1000</td>
<td style="text-align: left;">+0.057 (0.016)</td>
<td style="text-align: left;">0.516</td>
<td style="text-align: left;">93.1%</td>
<td style="text-align: left;">1.92</td>
</tr>
<tr class="even">
<td style="text-align: left;">scen2_lik_misspec_n3</td>
<td style="text-align: left;">Joint 4PL (absolute)</td>
<td style="text-align: left;">z</td>
<td style="text-align: right;">1000</td>
<td style="text-align: left;">+0.013 (0.016)</td>
<td style="text-align: left;">0.502</td>
<td style="text-align: left;">92.8%</td>
<td style="text-align: left;">1.86</td>
</tr>
<tr class="odd">
<td style="text-align: left;">scen2_lik_misspec_n3</td>
<td style="text-align: left;">Two-stage bin (Normal CI)</td>
<td style="text-align: left;">CTmax_1hr</td>
<td style="text-align: right;">1000</td>
<td style="text-align: left;">-0.009 (0.008)</td>
<td style="text-align: left;">0.257</td>
<td style="text-align: left;">89.5%</td>
<td style="text-align: left;">0.94</td>
</tr>
<tr class="even">
<td style="text-align: left;">scen2_lik_misspec_n3</td>
<td style="text-align: left;">Two-stage bin (t CI)</td>
<td style="text-align: left;">CTmax_1hr</td>
<td style="text-align: right;">1000</td>
<td style="text-align: left;">-0.009 (0.008)</td>
<td style="text-align: left;">0.257</td>
<td style="text-align: left;">96.5%</td>
<td style="text-align: left;">1.52</td>
</tr>
<tr class="odd">
<td style="text-align: left;">scen2_lik_misspec_n3</td>
<td style="text-align: left;">Two-stage BB (Normal CI)</td>
<td style="text-align: left;">CTmax_1hr</td>
<td style="text-align: right;">991</td>
<td style="text-align: left;">-0.024 (0.012)</td>
<td style="text-align: left;">0.387</td>
<td style="text-align: left;">89.2%</td>
<td style="text-align: left;">0.93</td>
</tr>
<tr class="even">
<td style="text-align: left;">scen2_lik_misspec_n3</td>
<td style="text-align: left;">Two-stage BB (t CI)</td>
<td style="text-align: left;">CTmax_1hr</td>
<td style="text-align: right;">991</td>
<td style="text-align: left;">-0.024 (0.012)</td>
<td style="text-align: left;">0.387</td>
<td style="text-align: left;">96.1%</td>
<td style="text-align: left;">1.52</td>
</tr>
<tr class="odd">
<td style="text-align: left;">scen2_lik_misspec_n3</td>
<td style="text-align: left;">Joint 4PL (relative)</td>
<td style="text-align: left;">CTmax_1hr</td>
<td style="text-align: right;">1000</td>
<td style="text-align: left;">-0.032 (0.007)</td>
<td style="text-align: left;">0.228</td>
<td style="text-align: left;">94.4%</td>
<td style="text-align: left;">0.92</td>
</tr>
<tr class="even">
<td style="text-align: left;">scen2_lik_misspec_n3</td>
<td style="text-align: left;">Joint 4PL (absolute)</td>
<td style="text-align: left;">CTmax_1hr</td>
<td style="text-align: right;">1000</td>
<td style="text-align: left;">-0.023 (0.007)</td>
<td style="text-align: left;">0.224</td>
<td style="text-align: left;">94.5%</td>
<td style="text-align: left;">0.91</td>
</tr>
<tr class="odd">
<td style="text-align: left;">scen2_lik_misspec_n5</td>
<td style="text-align: left;">Two-stage bin (Normal CI)</td>
<td style="text-align: left;">z</td>
<td style="text-align: right;">1000</td>
<td style="text-align: left;">-0.010 (0.012)</td>
<td style="text-align: left;">0.393</td>
<td style="text-align: left;">86.9%</td>
<td style="text-align: left;">1.35</td>
</tr>
<tr class="even">
<td style="text-align: left;">scen2_lik_misspec_n5</td>
<td style="text-align: left;">Two-stage bin (t CI)</td>
<td style="text-align: left;">z</td>
<td style="text-align: right;">1000</td>
<td style="text-align: left;">-0.010 (0.012)</td>
<td style="text-align: left;">0.393</td>
<td style="text-align: left;">95.6%</td>
<td style="text-align: left;">2.19</td>
</tr>
<tr class="odd">
<td style="text-align: left;">scen2_lik_misspec_n5</td>
<td style="text-align: left;">Two-stage BB (Normal CI)</td>
<td style="text-align: left;">z</td>
<td style="text-align: right;">999</td>
<td style="text-align: left;">-0.008 (0.014)</td>
<td style="text-align: left;">0.449</td>
<td style="text-align: left;">86.9%</td>
<td style="text-align: left;">1.30</td>
</tr>
<tr class="even">
<td style="text-align: left;">scen2_lik_misspec_n5</td>
<td style="text-align: left;">Two-stage BB (t CI)</td>
<td style="text-align: left;">z</td>
<td style="text-align: right;">999</td>
<td style="text-align: left;">-0.008 (0.014)</td>
<td style="text-align: left;">0.449</td>
<td style="text-align: left;">95.3%</td>
<td style="text-align: left;">2.11</td>
</tr>
<tr class="odd">
<td style="text-align: left;">scen2_lik_misspec_n5</td>
<td style="text-align: left;">Joint 4PL (relative)</td>
<td style="text-align: left;">z</td>
<td style="text-align: right;">1000</td>
<td style="text-align: left;">+0.036 (0.011)</td>
<td style="text-align: left;">0.352</td>
<td style="text-align: left;">95.5%</td>
<td style="text-align: left;">1.44</td>
</tr>
<tr class="even">
<td style="text-align: left;">scen2_lik_misspec_n5</td>
<td style="text-align: left;">Joint 4PL (absolute)</td>
<td style="text-align: left;">z</td>
<td style="text-align: right;">1000</td>
<td style="text-align: left;">+0.002 (0.011)</td>
<td style="text-align: left;">0.344</td>
<td style="text-align: left;">95.1%</td>
<td style="text-align: left;">1.40</td>
</tr>
<tr class="odd">
<td style="text-align: left;">scen2_lik_misspec_n5</td>
<td style="text-align: left;">Two-stage bin (Normal CI)</td>
<td style="text-align: left;">CTmax_1hr</td>
<td style="text-align: right;">1000</td>
<td style="text-align: left;">+0.002 (0.006)</td>
<td style="text-align: left;">0.196</td>
<td style="text-align: left;">88.3%</td>
<td style="text-align: left;">0.69</td>
</tr>
<tr class="even">
<td style="text-align: left;">scen2_lik_misspec_n5</td>
<td style="text-align: left;">Two-stage bin (t CI)</td>
<td style="text-align: left;">CTmax_1hr</td>
<td style="text-align: right;">1000</td>
<td style="text-align: left;">+0.002 (0.006)</td>
<td style="text-align: left;">0.196</td>
<td style="text-align: left;">96.5%</td>
<td style="text-align: left;">1.12</td>
</tr>
<tr class="odd">
<td style="text-align: left;">scen2_lik_misspec_n5</td>
<td style="text-align: left;">Two-stage BB (Normal CI)</td>
<td style="text-align: left;">CTmax_1hr</td>
<td style="text-align: right;">999</td>
<td style="text-align: left;">+0.005 (0.007)</td>
<td style="text-align: left;">0.229</td>
<td style="text-align: left;">87.3%</td>
<td style="text-align: left;">0.66</td>
</tr>
<tr class="even">
<td style="text-align: left;">scen2_lik_misspec_n5</td>
<td style="text-align: left;">Two-stage BB (t CI)</td>
<td style="text-align: left;">CTmax_1hr</td>
<td style="text-align: right;">999</td>
<td style="text-align: left;">+0.005 (0.007)</td>
<td style="text-align: left;">0.229</td>
<td style="text-align: left;">96.6%</td>
<td style="text-align: left;">1.07</td>
</tr>
<tr class="odd">
<td style="text-align: left;">scen2_lik_misspec_n5</td>
<td style="text-align: left;">Joint 4PL (relative)</td>
<td style="text-align: left;">CTmax_1hr</td>
<td style="text-align: right;">1000</td>
<td style="text-align: left;">-0.019 (0.006)</td>
<td style="text-align: left;">0.179</td>
<td style="text-align: left;">94.9%</td>
<td style="text-align: left;">0.71</td>
</tr>
<tr class="even">
<td style="text-align: left;">scen2_lik_misspec_n5</td>
<td style="text-align: left;">Joint 4PL (absolute)</td>
<td style="text-align: left;">CTmax_1hr</td>
<td style="text-align: right;">1000</td>
<td style="text-align: left;">-0.011 (0.006)</td>
<td style="text-align: left;">0.177</td>
<td style="text-align: left;">94.7%</td>
<td style="text-align: left;">0.69</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-scen2" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-scen2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="2026-05-16-two-stage-bias-sim-writeup_files/figure-html/fig-scen2-1.png" class="img-fluid figure-img" width="768">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-scen2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Scenario 2 (likelihood misspecification only, beta-binomial DGP). All three estimators stay within MC SE of zero bias on both quantities. Coverage of the two two-stage variants drops to 84–90%, regardless of Stage-1 family; joint 4PL coverage stays near nominal 0.95.
</figcaption>
</figure>
</div>
</div>
</div>
<p><strong>Read.</strong> Bias predictions held: all six estimators within MC SE of zero on both quantities. Normal-quantile two-stage coverage runs 84–89% on both quantities, regardless of Stage-1 family. <strong>The t-quantile correction lifts coverage to 93–97%</strong> — close enough to nominal that under overdispersion alone, the small-sample CI fix is sufficient without changing the architecture. The patched (BB) Stage 1 by itself does not rescue coverage; the Stage-2 OLS already reads dispersion off the per-T point spread, but under-propagates it under Normal CIs. Joint 4PL keeps coverage at 93–96% on both extracts; relative and absolute agree to within 0.01 °C on CTmax (asymptotes still at the boundary).</p>
</section>
<section id="scenario-3-heat-lowers-max-survival-asymmetric-u-drift" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Scenario 3 — Heat lowers max survival (asymmetric u drift)</h1>
<p><strong>Question.</strong> When the upper asymptote drops with temperature (intrinsic heat-induced mortality reduces the proportion of the cohort ever susceptible to the timed exposure) but neither two-stage estimator has an asymptote parameter, does the missing structure get absorbed into Stage 1’s effective midpoint, biasing <span class="math inline">\(z\)</span> and <span class="math inline">\(CT_{\max,1\text{h}}\)</span>?</p>
<p><strong>Prediction.</strong> Both two-stage variants should be biased on at least one quantity, with bias that does not shrink with <span class="math inline">\(n_{\text{reps}}\)</span>. Joint 4PL should be unbiased and calibrated.</p>
<p><strong>Design.</strong> DGP: <code>up</code> drops 1 pp/°C from baseline 0.92, <code>low</code> constant at 0.05, <code>k = 8</code>, midpoint linear in <span class="math inline">\(T\)</span> with slope <span class="math inline">\(-0.15\)</span>, beta-binomial likelihood (φ = 5). True <span class="math inline">\(z = 6.537\)</span>, true <span class="math inline">\(CT_{\max,1\text{h}} = 32.124\,^\circ\text{C}\)</span>. Two cells: <span class="math inline">\(n_{\text{reps}} \in \{3, 5\}\)</span>. <span class="math inline">\(N_{\text{sim}} = 1000\)</span> per cell.</p>
<div class="cell">
<div class="cell-output-display">
<div class="kable-table">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 23%">
<col style="width: 26%">
<col style="width: 10%">
<col style="width: 5%">
<col style="width: 15%">
<col style="width: 6%">
<col style="width: 9%">
<col style="width: 6%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Cell</th>
<th style="text-align: left;">Method</th>
<th style="text-align: left;">Quantity</th>
<th style="text-align: right;">n_ok</th>
<th style="text-align: left;">Bias</th>
<th style="text-align: left;">RMSE</th>
<th style="text-align: left;">Coverage</th>
<th style="text-align: left;">Width</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">scen3_heat_lowers_u_n3</td>
<td style="text-align: left;">Two-stage bin (Normal CI)</td>
<td style="text-align: left;">z</td>
<td style="text-align: right;">1000</td>
<td style="text-align: left;">-0.077 (0.023)</td>
<td style="text-align: left;">0.742</td>
<td style="text-align: left;">83.7%</td>
<td style="text-align: left;">2.40</td>
</tr>
<tr class="even">
<td style="text-align: left;">scen3_heat_lowers_u_n3</td>
<td style="text-align: left;">Two-stage bin (t CI)</td>
<td style="text-align: left;">z</td>
<td style="text-align: right;">1000</td>
<td style="text-align: left;">-0.077 (0.023)</td>
<td style="text-align: left;">0.742</td>
<td style="text-align: left;">93.7%</td>
<td style="text-align: left;">3.90</td>
</tr>
<tr class="odd">
<td style="text-align: left;">scen3_heat_lowers_u_n3</td>
<td style="text-align: left;">Two-stage BB (Normal CI)</td>
<td style="text-align: left;">z</td>
<td style="text-align: right;">1000</td>
<td style="text-align: left;">-0.135 (0.026)</td>
<td style="text-align: left;">0.825</td>
<td style="text-align: left;">82.9%</td>
<td style="text-align: left;">2.50</td>
</tr>
<tr class="even">
<td style="text-align: left;">scen3_heat_lowers_u_n3</td>
<td style="text-align: left;">Two-stage BB (t CI)</td>
<td style="text-align: left;">z</td>
<td style="text-align: right;">1000</td>
<td style="text-align: left;">-0.135 (0.026)</td>
<td style="text-align: left;">0.825</td>
<td style="text-align: left;">93.7%</td>
<td style="text-align: left;">4.07</td>
</tr>
<tr class="odd">
<td style="text-align: left;">scen3_heat_lowers_u_n3</td>
<td style="text-align: left;">Joint 4PL (relative)</td>
<td style="text-align: left;">z</td>
<td style="text-align: right;">1000</td>
<td style="text-align: left;">-0.034 (0.021)</td>
<td style="text-align: left;">0.651</td>
<td style="text-align: left;">94.6%</td>
<td style="text-align: left;">2.62</td>
</tr>
<tr class="even">
<td style="text-align: left;">scen3_heat_lowers_u_n3</td>
<td style="text-align: left;">Joint 4PL (absolute)</td>
<td style="text-align: left;">z</td>
<td style="text-align: right;">1000</td>
<td style="text-align: left;">-0.040 (0.019)</td>
<td style="text-align: left;">0.595</td>
<td style="text-align: left;">94.6%</td>
<td style="text-align: left;">2.35</td>
</tr>
<tr class="odd">
<td style="text-align: left;">scen3_heat_lowers_u_n3</td>
<td style="text-align: left;">Two-stage bin (Normal CI)</td>
<td style="text-align: left;">CTmax_1hr</td>
<td style="text-align: right;">1000</td>
<td style="text-align: left;">-0.273 (0.011)</td>
<td style="text-align: left;">0.450</td>
<td style="text-align: left;">86.7%</td>
<td style="text-align: left;">1.35</td>
</tr>
<tr class="even">
<td style="text-align: left;">scen3_heat_lowers_u_n3</td>
<td style="text-align: left;">Two-stage bin (t CI)</td>
<td style="text-align: left;">CTmax_1hr</td>
<td style="text-align: right;">1000</td>
<td style="text-align: left;">-0.273 (0.011)</td>
<td style="text-align: left;">0.450</td>
<td style="text-align: left;">96.2%</td>
<td style="text-align: left;">2.19</td>
</tr>
<tr class="odd">
<td style="text-align: left;">scen3_heat_lowers_u_n3</td>
<td style="text-align: left;">Two-stage BB (Normal CI)</td>
<td style="text-align: left;">CTmax_1hr</td>
<td style="text-align: right;">1000</td>
<td style="text-align: left;">-0.362 (0.014)</td>
<td style="text-align: left;">0.568</td>
<td style="text-align: left;">84.5%</td>
<td style="text-align: left;">1.41</td>
</tr>
<tr class="even">
<td style="text-align: left;">scen3_heat_lowers_u_n3</td>
<td style="text-align: left;">Two-stage BB (t CI)</td>
<td style="text-align: left;">CTmax_1hr</td>
<td style="text-align: right;">1000</td>
<td style="text-align: left;">-0.362 (0.014)</td>
<td style="text-align: left;">0.568</td>
<td style="text-align: left;">94.9%</td>
<td style="text-align: left;">2.29</td>
</tr>
<tr class="odd">
<td style="text-align: left;">scen3_heat_lowers_u_n3</td>
<td style="text-align: left;">Joint 4PL (relative)</td>
<td style="text-align: left;">CTmax_1hr</td>
<td style="text-align: right;">1000</td>
<td style="text-align: left;">-0.021 (0.009)</td>
<td style="text-align: left;">0.295</td>
<td style="text-align: left;">95.3%</td>
<td style="text-align: left;">1.20</td>
</tr>
<tr class="even">
<td style="text-align: left;">scen3_heat_lowers_u_n3</td>
<td style="text-align: left;">Joint 4PL (absolute)</td>
<td style="text-align: left;">CTmax_1hr</td>
<td style="text-align: right;">1000</td>
<td style="text-align: left;">-0.019 (0.009)</td>
<td style="text-align: left;">0.281</td>
<td style="text-align: left;">95.3%</td>
<td style="text-align: left;">1.12</td>
</tr>
<tr class="odd">
<td style="text-align: left;">scen3_heat_lowers_u_n5</td>
<td style="text-align: left;">Two-stage bin (Normal CI)</td>
<td style="text-align: left;">z</td>
<td style="text-align: right;">1000</td>
<td style="text-align: left;">-0.099 (0.017)</td>
<td style="text-align: left;">0.554</td>
<td style="text-align: left;">84.1%</td>
<td style="text-align: left;">1.85</td>
</tr>
<tr class="even">
<td style="text-align: left;">scen3_heat_lowers_u_n5</td>
<td style="text-align: left;">Two-stage bin (t CI)</td>
<td style="text-align: left;">z</td>
<td style="text-align: right;">1000</td>
<td style="text-align: left;">-0.099 (0.017)</td>
<td style="text-align: left;">0.554</td>
<td style="text-align: left;">94.4%</td>
<td style="text-align: left;">3.01</td>
</tr>
<tr class="odd">
<td style="text-align: left;">scen3_heat_lowers_u_n5</td>
<td style="text-align: left;">Two-stage BB (Normal CI)</td>
<td style="text-align: left;">z</td>
<td style="text-align: right;">1000</td>
<td style="text-align: left;">-0.172 (0.019)</td>
<td style="text-align: left;">0.619</td>
<td style="text-align: left;">80.4%</td>
<td style="text-align: left;">1.98</td>
</tr>
<tr class="even">
<td style="text-align: left;">scen3_heat_lowers_u_n5</td>
<td style="text-align: left;">Two-stage BB (t CI)</td>
<td style="text-align: left;">z</td>
<td style="text-align: right;">1000</td>
<td style="text-align: left;">-0.172 (0.019)</td>
<td style="text-align: left;">0.619</td>
<td style="text-align: left;">92.8%</td>
<td style="text-align: left;">3.21</td>
</tr>
<tr class="odd">
<td style="text-align: left;">scen3_heat_lowers_u_n5</td>
<td style="text-align: left;">Joint 4PL (relative)</td>
<td style="text-align: left;">z</td>
<td style="text-align: right;">1000</td>
<td style="text-align: left;">-0.070 (0.015)</td>
<td style="text-align: left;">0.481</td>
<td style="text-align: left;">95.6%</td>
<td style="text-align: left;">1.97</td>
</tr>
<tr class="even">
<td style="text-align: left;">scen3_heat_lowers_u_n5</td>
<td style="text-align: left;">Joint 4PL (absolute)</td>
<td style="text-align: left;">z</td>
<td style="text-align: right;">1000</td>
<td style="text-align: left;">-0.064 (0.014)</td>
<td style="text-align: left;">0.445</td>
<td style="text-align: left;">96.1%</td>
<td style="text-align: left;">1.79</td>
</tr>
<tr class="odd">
<td style="text-align: left;">scen3_heat_lowers_u_n5</td>
<td style="text-align: left;">Two-stage bin (Normal CI)</td>
<td style="text-align: left;">CTmax_1hr</td>
<td style="text-align: right;">1000</td>
<td style="text-align: left;">-0.265 (0.009)</td>
<td style="text-align: left;">0.388</td>
<td style="text-align: left;">81.0%</td>
<td style="text-align: left;">1.04</td>
</tr>
<tr class="even">
<td style="text-align: left;">scen3_heat_lowers_u_n5</td>
<td style="text-align: left;">Two-stage bin (t CI)</td>
<td style="text-align: left;">CTmax_1hr</td>
<td style="text-align: right;">1000</td>
<td style="text-align: left;">-0.265 (0.009)</td>
<td style="text-align: left;">0.388</td>
<td style="text-align: left;">93.0%</td>
<td style="text-align: left;">1.69</td>
</tr>
<tr class="odd">
<td style="text-align: left;">scen3_heat_lowers_u_n5</td>
<td style="text-align: left;">Two-stage BB (Normal CI)</td>
<td style="text-align: left;">CTmax_1hr</td>
<td style="text-align: right;">1000</td>
<td style="text-align: left;">-0.351 (0.010)</td>
<td style="text-align: left;">0.469</td>
<td style="text-align: left;">74.9%</td>
<td style="text-align: left;">1.13</td>
</tr>
<tr class="even">
<td style="text-align: left;">scen3_heat_lowers_u_n5</td>
<td style="text-align: left;">Two-stage BB (t CI)</td>
<td style="text-align: left;">CTmax_1hr</td>
<td style="text-align: right;">1000</td>
<td style="text-align: left;">-0.351 (0.010)</td>
<td style="text-align: left;">0.469</td>
<td style="text-align: left;">91.1%</td>
<td style="text-align: left;">1.83</td>
</tr>
<tr class="odd">
<td style="text-align: left;">scen3_heat_lowers_u_n5</td>
<td style="text-align: left;">Joint 4PL (relative)</td>
<td style="text-align: left;">CTmax_1hr</td>
<td style="text-align: right;">1000</td>
<td style="text-align: left;">+0.012 (0.007)</td>
<td style="text-align: left;">0.229</td>
<td style="text-align: left;">95.5%</td>
<td style="text-align: left;">0.90</td>
</tr>
<tr class="even">
<td style="text-align: left;">scen3_heat_lowers_u_n5</td>
<td style="text-align: left;">Joint 4PL (absolute)</td>
<td style="text-align: left;">CTmax_1hr</td>
<td style="text-align: right;">1000</td>
<td style="text-align: left;">+0.009 (0.007)</td>
<td style="text-align: left;">0.216</td>
<td style="text-align: left;">94.9%</td>
<td style="text-align: left;">0.85</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-scen3" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-scen3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="2026-05-16-two-stage-bias-sim-writeup_files/figure-html/fig-scen3-1.png" class="img-fluid figure-img" width="768">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-scen3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: Scenario 3 (asymmetric u drift, beta-binomial). Two-stage CTmax bias is systematically negative (~ −0.27 to −0.36 °C) and does not shrink with <span class="math inline">\(n_{reps}\)</span>; coverage on the BB CTmax falls to 75% at <span class="math inline">\(n_{reps}=5\)</span>. Joint 4PL bias is within MC SE on CTmax in both cells; small positive z bias persists (+0.06 to +0.10) but coverage stays at 94–96%.
</figcaption>
</figure>
</div>
</div>
</div>
<p><strong>Read.</strong> Two-stage CTmax bias is systematically negative across both cells (−0.27 °C binomial, −0.36 °C beta-binomial) and <strong>does not shrink with <span class="math inline">\(n_{\text{reps}}\)</span></strong>. Normal-CI coverage on the BB CTmax drops to 75% at <span class="math inline">\(n_{\text{reps}}=5\)</span>; the t-correction lifts it to 91% but cannot reach nominal because the bias is too large for any CI inflation to fully catch. The bin-Stage-1 + t-CI variant at 93% is closer to nominal because its bias is smaller (−0.27 vs −0.35 °C).</p>
<p><strong>Joint 4PL absorbs the T-varying <code>up</code>.</strong> Both extracts cover at 95% on CTmax with bias within MC SE: <code>joint_4pl</code> (relative) +0.034 / +0.001 °C; <code>joint_4pl_abs</code> +0.009 / −0.019 °C. <strong>The absolute extract trims the small positive z bias that the relative extract carries</strong> (+0.06–0.10 → −0.04 to −0.06 °C). Both at 95% z coverage.</p>
</section>
<section id="scenario-4-asymptotes-compress-symmetric-drift" class="level1" data-number="6">
<h1 data-number="6"><span class="header-section-number">6</span> Scenario 4 — Asymptotes compress (symmetric drift)</h1>
<p><strong>Question.</strong> When <em>both</em> asymptotes drift toward each other symmetrically (<code>up</code> drops, <code>low</code> rises), the logit-difference is nearly preserved but the curve range shrinks. How does each estimator handle this in <span class="math inline">\(z\)</span> and <span class="math inline">\(CT_{\max,1\text{h}}\)</span>?</p>
<p><strong>Prediction.</strong> True <span class="math inline">\(z\)</span> barely changes (the slope around the midpoint is preserved). Two-stage methods should show smaller bias than Scenario 3 because the symmetric perturbation partially cancels at the midpoint. Joint 4PL near-nominal.</p>
<p><strong>Design.</strong> <code>up</code> drops 1 pp/°C from baseline 0.92; <code>low</code> rises 1 pp/°C from baseline 0.05; <code>k = 8</code>; midpoint linear in <span class="math inline">\(T\)</span> with slope <span class="math inline">\(-0.15\)</span>; beta-binomial likelihood (φ = 5). True <span class="math inline">\(z = 6.658\)</span>, true <span class="math inline">\(CT_{\max,1\text{h}} = 32.090\,^\circ\text{C}\)</span>. Two cells: <span class="math inline">\(n_{\text{reps}} \in \{3, 5\}\)</span>. <span class="math inline">\(N_{\text{sim}} = 1000\)</span> per cell.</p>
<div class="cell">
<div class="cell-output-display">
<div class="kable-table">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 18%">
<col style="width: 27%">
<col style="width: 10%">
<col style="width: 5%">
<col style="width: 15%">
<col style="width: 6%">
<col style="width: 9%">
<col style="width: 6%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Cell</th>
<th style="text-align: left;">Method</th>
<th style="text-align: left;">Quantity</th>
<th style="text-align: right;">n_ok</th>
<th style="text-align: left;">Bias</th>
<th style="text-align: left;">RMSE</th>
<th style="text-align: left;">Coverage</th>
<th style="text-align: left;">Width</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">scen4_compress_n3</td>
<td style="text-align: left;">Two-stage bin (Normal CI)</td>
<td style="text-align: left;">z</td>
<td style="text-align: right;">1000</td>
<td style="text-align: left;">+0.391 (0.029)</td>
<td style="text-align: left;">1.010</td>
<td style="text-align: left;">84.4%</td>
<td style="text-align: left;">2.82</td>
</tr>
<tr class="even">
<td style="text-align: left;">scen4_compress_n3</td>
<td style="text-align: left;">Two-stage bin (t CI)</td>
<td style="text-align: left;">z</td>
<td style="text-align: right;">1000</td>
<td style="text-align: left;">+0.391 (0.029)</td>
<td style="text-align: left;">1.010</td>
<td style="text-align: left;">95.2%</td>
<td style="text-align: left;">4.59</td>
</tr>
<tr class="odd">
<td style="text-align: left;">scen4_compress_n3</td>
<td style="text-align: left;">Two-stage BB (Normal CI)</td>
<td style="text-align: left;">z</td>
<td style="text-align: right;">1000</td>
<td style="text-align: left;">+0.553 (0.033)</td>
<td style="text-align: left;">1.186</td>
<td style="text-align: left;">86.2%</td>
<td style="text-align: left;">3.29</td>
</tr>
<tr class="even">
<td style="text-align: left;">scen4_compress_n3</td>
<td style="text-align: left;">Two-stage BB (t CI)</td>
<td style="text-align: left;">z</td>
<td style="text-align: right;">1000</td>
<td style="text-align: left;">+0.553 (0.033)</td>
<td style="text-align: left;">1.186</td>
<td style="text-align: left;">96.2%</td>
<td style="text-align: left;">5.34</td>
</tr>
<tr class="odd">
<td style="text-align: left;">scen4_compress_n3</td>
<td style="text-align: left;">Joint 4PL (relative)</td>
<td style="text-align: left;">z</td>
<td style="text-align: right;">1000</td>
<td style="text-align: left;">+0.084 (0.022)</td>
<td style="text-align: left;">0.691</td>
<td style="text-align: left;">94.3%</td>
<td style="text-align: left;">2.72</td>
</tr>
<tr class="even">
<td style="text-align: left;">scen4_compress_n3</td>
<td style="text-align: left;">Joint 4PL (absolute)</td>
<td style="text-align: left;">z</td>
<td style="text-align: right;">1000</td>
<td style="text-align: left;">+0.076 (0.021)</td>
<td style="text-align: left;">0.653</td>
<td style="text-align: left;">94.2%</td>
<td style="text-align: left;">2.51</td>
</tr>
<tr class="odd">
<td style="text-align: left;">scen4_compress_n3</td>
<td style="text-align: left;">Two-stage bin (Normal CI)</td>
<td style="text-align: left;">CTmax_1hr</td>
<td style="text-align: right;">1000</td>
<td style="text-align: left;">-0.382 (0.012)</td>
<td style="text-align: left;">0.542</td>
<td style="text-align: left;">84.1%</td>
<td style="text-align: left;">1.50</td>
</tr>
<tr class="even">
<td style="text-align: left;">scen4_compress_n3</td>
<td style="text-align: left;">Two-stage bin (t CI)</td>
<td style="text-align: left;">CTmax_1hr</td>
<td style="text-align: right;">1000</td>
<td style="text-align: left;">-0.382 (0.012)</td>
<td style="text-align: left;">0.542</td>
<td style="text-align: left;">93.6%</td>
<td style="text-align: left;">2.43</td>
</tr>
<tr class="odd">
<td style="text-align: left;">scen4_compress_n3</td>
<td style="text-align: left;">Two-stage BB (Normal CI)</td>
<td style="text-align: left;">CTmax_1hr</td>
<td style="text-align: right;">1000</td>
<td style="text-align: left;">-0.569 (0.014)</td>
<td style="text-align: left;">0.717</td>
<td style="text-align: left;">78.9%</td>
<td style="text-align: left;">1.74</td>
</tr>
<tr class="even">
<td style="text-align: left;">scen4_compress_n3</td>
<td style="text-align: left;">Two-stage BB (t CI)</td>
<td style="text-align: left;">CTmax_1hr</td>
<td style="text-align: right;">1000</td>
<td style="text-align: left;">-0.569 (0.014)</td>
<td style="text-align: left;">0.717</td>
<td style="text-align: left;">92.9%</td>
<td style="text-align: left;">2.83</td>
</tr>
<tr class="odd">
<td style="text-align: left;">scen4_compress_n3</td>
<td style="text-align: left;">Joint 4PL (relative)</td>
<td style="text-align: left;">CTmax_1hr</td>
<td style="text-align: right;">1000</td>
<td style="text-align: left;">-0.065 (0.009)</td>
<td style="text-align: left;">0.302</td>
<td style="text-align: left;">93.7%</td>
<td style="text-align: left;">1.14</td>
</tr>
<tr class="even">
<td style="text-align: left;">scen4_compress_n3</td>
<td style="text-align: left;">Joint 4PL (absolute)</td>
<td style="text-align: left;">CTmax_1hr</td>
<td style="text-align: right;">1000</td>
<td style="text-align: left;">-0.046 (0.009)</td>
<td style="text-align: left;">0.292</td>
<td style="text-align: left;">93.9%</td>
<td style="text-align: left;">1.10</td>
</tr>
<tr class="odd">
<td style="text-align: left;">scen4_compress_n5</td>
<td style="text-align: left;">Two-stage bin (Normal CI)</td>
<td style="text-align: left;">z</td>
<td style="text-align: right;">1000</td>
<td style="text-align: left;">+0.395 (0.023)</td>
<td style="text-align: left;">0.820</td>
<td style="text-align: left;">82.7%</td>
<td style="text-align: left;">2.25</td>
</tr>
<tr class="even">
<td style="text-align: left;">scen4_compress_n5</td>
<td style="text-align: left;">Two-stage bin (t CI)</td>
<td style="text-align: left;">z</td>
<td style="text-align: right;">1000</td>
<td style="text-align: left;">+0.395 (0.023)</td>
<td style="text-align: left;">0.820</td>
<td style="text-align: left;">94.5%</td>
<td style="text-align: left;">3.65</td>
</tr>
<tr class="odd">
<td style="text-align: left;">scen4_compress_n5</td>
<td style="text-align: left;">Two-stage BB (Normal CI)</td>
<td style="text-align: left;">z</td>
<td style="text-align: right;">1000</td>
<td style="text-align: left;">+0.560 (0.025)</td>
<td style="text-align: left;">0.978</td>
<td style="text-align: left;">83.1%</td>
<td style="text-align: left;">2.55</td>
</tr>
<tr class="even">
<td style="text-align: left;">scen4_compress_n5</td>
<td style="text-align: left;">Two-stage BB (t CI)</td>
<td style="text-align: left;">z</td>
<td style="text-align: right;">1000</td>
<td style="text-align: left;">+0.560 (0.025)</td>
<td style="text-align: left;">0.978</td>
<td style="text-align: left;">94.5%</td>
<td style="text-align: left;">4.13</td>
</tr>
<tr class="odd">
<td style="text-align: left;">scen4_compress_n5</td>
<td style="text-align: left;">Joint 4PL (relative)</td>
<td style="text-align: left;">z</td>
<td style="text-align: right;">1000</td>
<td style="text-align: left;">+0.029 (0.016)</td>
<td style="text-align: left;">0.499</td>
<td style="text-align: left;">94.4%</td>
<td style="text-align: left;">1.97</td>
</tr>
<tr class="even">
<td style="text-align: left;">scen4_compress_n5</td>
<td style="text-align: left;">Joint 4PL (absolute)</td>
<td style="text-align: left;">z</td>
<td style="text-align: right;">1000</td>
<td style="text-align: left;">+0.035 (0.015)</td>
<td style="text-align: left;">0.480</td>
<td style="text-align: left;">94.3%</td>
<td style="text-align: left;">1.86</td>
</tr>
<tr class="odd">
<td style="text-align: left;">scen4_compress_n5</td>
<td style="text-align: left;">Two-stage bin (Normal CI)</td>
<td style="text-align: left;">CTmax_1hr</td>
<td style="text-align: right;">1000</td>
<td style="text-align: left;">-0.387 (0.009)</td>
<td style="text-align: left;">0.490</td>
<td style="text-align: left;">75.6%</td>
<td style="text-align: left;">1.18</td>
</tr>
<tr class="even">
<td style="text-align: left;">scen4_compress_n5</td>
<td style="text-align: left;">Two-stage bin (t CI)</td>
<td style="text-align: left;">CTmax_1hr</td>
<td style="text-align: right;">1000</td>
<td style="text-align: left;">-0.387 (0.009)</td>
<td style="text-align: left;">0.490</td>
<td style="text-align: left;">91.3%</td>
<td style="text-align: left;">1.91</td>
</tr>
<tr class="odd">
<td style="text-align: left;">scen4_compress_n5</td>
<td style="text-align: left;">Two-stage BB (Normal CI)</td>
<td style="text-align: left;">CTmax_1hr</td>
<td style="text-align: right;">1000</td>
<td style="text-align: left;">-0.581 (0.011)</td>
<td style="text-align: left;">0.678</td>
<td style="text-align: left;">64.2%</td>
<td style="text-align: left;">1.35</td>
</tr>
<tr class="even">
<td style="text-align: left;">scen4_compress_n5</td>
<td style="text-align: left;">Two-stage BB (t CI)</td>
<td style="text-align: left;">CTmax_1hr</td>
<td style="text-align: right;">1000</td>
<td style="text-align: left;">-0.581 (0.011)</td>
<td style="text-align: left;">0.678</td>
<td style="text-align: left;">87.1%</td>
<td style="text-align: left;">2.19</td>
</tr>
<tr class="odd">
<td style="text-align: left;">scen4_compress_n5</td>
<td style="text-align: left;">Joint 4PL (relative)</td>
<td style="text-align: left;">CTmax_1hr</td>
<td style="text-align: right;">1000</td>
<td style="text-align: left;">-0.034 (0.007)</td>
<td style="text-align: left;">0.219</td>
<td style="text-align: left;">94.5%</td>
<td style="text-align: left;">0.84</td>
</tr>
<tr class="even">
<td style="text-align: left;">scen4_compress_n5</td>
<td style="text-align: left;">Joint 4PL (absolute)</td>
<td style="text-align: left;">CTmax_1hr</td>
<td style="text-align: right;">1000</td>
<td style="text-align: left;">-0.023 (0.007)</td>
<td style="text-align: left;">0.212</td>
<td style="text-align: left;">94.9%</td>
<td style="text-align: left;">0.82</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-scen4" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-scen4-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="2026-05-16-two-stage-bias-sim-writeup_files/figure-html/fig-scen4-1.png" class="img-fluid figure-img" width="768">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-scen4-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: Scenario 4 (asymptotes compress). Two-stage z bias <em>flips sign relative to Scenario 3</em>: now positive (+0.39 binomial, +0.55 beta-binomial). CTmax bias remains negative and grows (~ −0.38 to −0.58 °C). Coverage on the BB CTmax falls to 64% at <span class="math inline">\(n_{reps}=5\)</span>. Joint 4PL coverage holds at 94–95%.
</figcaption>
</figure>
</div>
</div>
</div>
<p><strong>Read.</strong> Two-stage CTmax bias is now larger than in Scenario 3 (−0.38 °C binomial, −0.58 °C beta-binomial) and the <span class="math inline">\(z\)</span> bias <strong>flips sign</strong>: where Scenario 3 had two-stage <span class="math inline">\(z\)</span> biased low (−0.08 to −0.17), Scenario 4 has it biased high (+0.39 to +0.56). Biases are insensitive to <span class="math inline">\(n_{\text{reps}}\)</span> — model misspecification, not sampling noise. Normal-CI coverage on the BB CTmax drops to 64% at <span class="math inline">\(n_{\text{reps}}=5\)</span>.</p>
<p><strong>The t-correction partially rescues coverage</strong>: BB CTmax 64% → 87%, bin CTmax 76% → 91% (at <span class="math inline">\(n_{\text{reps}}=5\)</span>). On z, the t-correction reaches nominal (94–95%) because the relative bias-to-CI ratio is smaller. The patched (BB) Stage-1 is consistently <em>worse</em> than the binomial Stage-1 on both quantities here, contradicting the prediction that the patch would help.</p>
<p><strong>Joint 4PL holds bias within MC SE on CTmax</strong> for both extracts (rel −0.009 / +0.021 °C; abs −0.046 / −0.023 °C) with 94–95% coverage. The absolute extract again trims the small positive z bias (+0.09 → +0.08; +0.04 → +0.03 °C) — modest but consistent.</p>
</section>
<section id="scenario-5-heat-sharpens-curve-varying-k" class="level1" data-number="7">
<h1 data-number="7"><span class="header-section-number">7</span> Scenario 5 — Heat sharpens curve (varying k)</h1>
<p><strong>Question.</strong> When the slope <span class="math inline">\(k\)</span> varies with temperature (curves get sharper as it gets hotter), the per-T binomial GLM still recovers a midpoint, but the Stage-2 OLS regression of <span class="math inline">\(\log_{10}\text{LT}_{50}\)</span> on <span class="math inline">\(T\)</span> assumes a linear relationship. How robust is the two-stage to T-varying <span class="math inline">\(k\)</span>?</p>
<p><strong>Prediction.</strong> Smallest bias of the shape-perturbing scenarios. Two stage variants: slight bias, coverage near nominal. Joint 4PL: bias within MC SE, calibrated.</p>
<p><strong>Design.</strong> <code>up = 0.92</code>, <code>low = 0.05</code>, <span class="math inline">\(k\)</span> linear in <span class="math inline">\(T\)</span> (8 at <span class="math inline">\(T=34\)</span>, slope +0.25 — so k = 7 at T=30, k = 9 at T=38). Midpoint linear in <span class="math inline">\(T\)</span> with slope <span class="math inline">\(-0.15\)</span>. Beta-binomial likelihood (φ = 5). True <span class="math inline">\(z = 6.679\)</span>, true <span class="math inline">\(CT_{\max,1\text{h}} = 32.084\,^\circ\text{C}\)</span>. Two cells: <span class="math inline">\(n_{\text{reps}} \in \{3, 5\}\)</span>. <span class="math inline">\(N_{\text{sim}} = 1000\)</span> per cell.</p>
<div class="cell">
<div class="cell-output-display">
<div class="kable-table">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 18%">
<col style="width: 27%">
<col style="width: 10%">
<col style="width: 5%">
<col style="width: 15%">
<col style="width: 6%">
<col style="width: 9%">
<col style="width: 6%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Cell</th>
<th style="text-align: left;">Method</th>
<th style="text-align: left;">Quantity</th>
<th style="text-align: right;">n_ok</th>
<th style="text-align: left;">Bias</th>
<th style="text-align: left;">RMSE</th>
<th style="text-align: left;">Coverage</th>
<th style="text-align: left;">Width</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">scen5_sharpen_n3</td>
<td style="text-align: left;">Two-stage bin (Normal CI)</td>
<td style="text-align: left;">z</td>
<td style="text-align: right;">1000</td>
<td style="text-align: left;">+0.452 (0.028)</td>
<td style="text-align: left;">0.986</td>
<td style="text-align: left;">85.9%</td>
<td style="text-align: left;">2.93</td>
</tr>
<tr class="even">
<td style="text-align: left;">scen5_sharpen_n3</td>
<td style="text-align: left;">Two-stage bin (t CI)</td>
<td style="text-align: left;">z</td>
<td style="text-align: right;">1000</td>
<td style="text-align: left;">+0.452 (0.028)</td>
<td style="text-align: left;">0.986</td>
<td style="text-align: left;">95.6%</td>
<td style="text-align: left;">4.76</td>
</tr>
<tr class="odd">
<td style="text-align: left;">scen5_sharpen_n3</td>
<td style="text-align: left;">Two-stage BB (Normal CI)</td>
<td style="text-align: left;">z</td>
<td style="text-align: right;">1000</td>
<td style="text-align: left;">+0.539 (0.033)</td>
<td style="text-align: left;">1.181</td>
<td style="text-align: left;">86.8%</td>
<td style="text-align: left;">3.27</td>
</tr>
<tr class="even">
<td style="text-align: left;">scen5_sharpen_n3</td>
<td style="text-align: left;">Two-stage BB (t CI)</td>
<td style="text-align: left;">z</td>
<td style="text-align: right;">1000</td>
<td style="text-align: left;">+0.539 (0.033)</td>
<td style="text-align: left;">1.181</td>
<td style="text-align: left;">95.4%</td>
<td style="text-align: left;">5.31</td>
</tr>
<tr class="odd">
<td style="text-align: left;">scen5_sharpen_n3</td>
<td style="text-align: left;">Joint 4PL (relative)</td>
<td style="text-align: left;">z</td>
<td style="text-align: right;">1000</td>
<td style="text-align: left;">+0.030 (0.021)</td>
<td style="text-align: left;">0.650</td>
<td style="text-align: left;">95.3%</td>
<td style="text-align: left;">2.70</td>
</tr>
<tr class="even">
<td style="text-align: left;">scen5_sharpen_n3</td>
<td style="text-align: left;">Joint 4PL (absolute)</td>
<td style="text-align: left;">z</td>
<td style="text-align: right;">1000</td>
<td style="text-align: left;">+0.047 (0.019)</td>
<td style="text-align: left;">0.617</td>
<td style="text-align: left;">95.5%</td>
<td style="text-align: left;">2.57</td>
</tr>
<tr class="odd">
<td style="text-align: left;">scen5_sharpen_n3</td>
<td style="text-align: left;">Two-stage bin (Normal CI)</td>
<td style="text-align: left;">CTmax_1hr</td>
<td style="text-align: right;">1000</td>
<td style="text-align: left;">-0.444 (0.015)</td>
<td style="text-align: left;">0.647</td>
<td style="text-align: left;">78.5%</td>
<td style="text-align: left;">1.56</td>
</tr>
<tr class="even">
<td style="text-align: left;">scen5_sharpen_n3</td>
<td style="text-align: left;">Two-stage bin (t CI)</td>
<td style="text-align: left;">CTmax_1hr</td>
<td style="text-align: right;">1000</td>
<td style="text-align: left;">-0.444 (0.015)</td>
<td style="text-align: left;">0.647</td>
<td style="text-align: left;">92.7%</td>
<td style="text-align: left;">2.53</td>
</tr>
<tr class="odd">
<td style="text-align: left;">scen5_sharpen_n3</td>
<td style="text-align: left;">Two-stage BB (Normal CI)</td>
<td style="text-align: left;">CTmax_1hr</td>
<td style="text-align: right;">1000</td>
<td style="text-align: left;">-0.609 (0.018)</td>
<td style="text-align: left;">0.834</td>
<td style="text-align: left;">73.0%</td>
<td style="text-align: left;">1.74</td>
</tr>
<tr class="even">
<td style="text-align: left;">scen5_sharpen_n3</td>
<td style="text-align: left;">Two-stage BB (t CI)</td>
<td style="text-align: left;">CTmax_1hr</td>
<td style="text-align: right;">1000</td>
<td style="text-align: left;">-0.609 (0.018)</td>
<td style="text-align: left;">0.834</td>
<td style="text-align: left;">91.3%</td>
<td style="text-align: left;">2.83</td>
</tr>
<tr class="odd">
<td style="text-align: left;">scen5_sharpen_n3</td>
<td style="text-align: left;">Joint 4PL (relative)</td>
<td style="text-align: left;">CTmax_1hr</td>
<td style="text-align: right;">1000</td>
<td style="text-align: left;">-0.034 (0.011)</td>
<td style="text-align: left;">0.348</td>
<td style="text-align: left;">92.6%</td>
<td style="text-align: left;">1.35</td>
</tr>
<tr class="even">
<td style="text-align: left;">scen5_sharpen_n3</td>
<td style="text-align: left;">Joint 4PL (absolute)</td>
<td style="text-align: left;">CTmax_1hr</td>
<td style="text-align: right;">1000</td>
<td style="text-align: left;">-0.032 (0.011)</td>
<td style="text-align: left;">0.335</td>
<td style="text-align: left;">93.3%</td>
<td style="text-align: left;">1.30</td>
</tr>
<tr class="odd">
<td style="text-align: left;">scen5_sharpen_n5</td>
<td style="text-align: left;">Two-stage bin (Normal CI)</td>
<td style="text-align: left;">z</td>
<td style="text-align: right;">1000</td>
<td style="text-align: left;">+0.470 (0.023)</td>
<td style="text-align: left;">0.861</td>
<td style="text-align: left;">84.3%</td>
<td style="text-align: left;">2.43</td>
</tr>
<tr class="even">
<td style="text-align: left;">scen5_sharpen_n5</td>
<td style="text-align: left;">Two-stage bin (t CI)</td>
<td style="text-align: left;">z</td>
<td style="text-align: right;">1000</td>
<td style="text-align: left;">+0.470 (0.023)</td>
<td style="text-align: left;">0.861</td>
<td style="text-align: left;">95.6%</td>
<td style="text-align: left;">3.94</td>
</tr>
<tr class="odd">
<td style="text-align: left;">scen5_sharpen_n5</td>
<td style="text-align: left;">Two-stage BB (Normal CI)</td>
<td style="text-align: left;">z</td>
<td style="text-align: right;">1000</td>
<td style="text-align: left;">+0.551 (0.027)</td>
<td style="text-align: left;">1.014</td>
<td style="text-align: left;">84.2%</td>
<td style="text-align: left;">2.63</td>
</tr>
<tr class="even">
<td style="text-align: left;">scen5_sharpen_n5</td>
<td style="text-align: left;">Two-stage BB (t CI)</td>
<td style="text-align: left;">z</td>
<td style="text-align: right;">1000</td>
<td style="text-align: left;">+0.551 (0.027)</td>
<td style="text-align: left;">1.014</td>
<td style="text-align: left;">95.0%</td>
<td style="text-align: left;">4.28</td>
</tr>
<tr class="odd">
<td style="text-align: left;">scen5_sharpen_n5</td>
<td style="text-align: left;">Joint 4PL (relative)</td>
<td style="text-align: left;">z</td>
<td style="text-align: right;">1000</td>
<td style="text-align: left;">+0.004 (0.016)</td>
<td style="text-align: left;">0.513</td>
<td style="text-align: left;">94.7%</td>
<td style="text-align: left;">2.04</td>
</tr>
<tr class="even">
<td style="text-align: left;">scen5_sharpen_n5</td>
<td style="text-align: left;">Joint 4PL (absolute)</td>
<td style="text-align: left;">z</td>
<td style="text-align: right;">1000</td>
<td style="text-align: left;">+0.029 (0.015)</td>
<td style="text-align: left;">0.491</td>
<td style="text-align: left;">94.0%</td>
<td style="text-align: left;">1.92</td>
</tr>
<tr class="odd">
<td style="text-align: left;">scen5_sharpen_n5</td>
<td style="text-align: left;">Two-stage bin (Normal CI)</td>
<td style="text-align: left;">CTmax_1hr</td>
<td style="text-align: right;">1000</td>
<td style="text-align: left;">-0.464 (0.011)</td>
<td style="text-align: left;">0.589</td>
<td style="text-align: left;">69.1%</td>
<td style="text-align: left;">1.25</td>
</tr>
<tr class="even">
<td style="text-align: left;">scen5_sharpen_n5</td>
<td style="text-align: left;">Two-stage bin (t CI)</td>
<td style="text-align: left;">CTmax_1hr</td>
<td style="text-align: right;">1000</td>
<td style="text-align: left;">-0.464 (0.011)</td>
<td style="text-align: left;">0.589</td>
<td style="text-align: left;">89.6%</td>
<td style="text-align: left;">2.03</td>
</tr>
<tr class="odd">
<td style="text-align: left;">scen5_sharpen_n5</td>
<td style="text-align: left;">Two-stage BB (Normal CI)</td>
<td style="text-align: left;">CTmax_1hr</td>
<td style="text-align: right;">1000</td>
<td style="text-align: left;">-0.623 (0.013)</td>
<td style="text-align: left;">0.753</td>
<td style="text-align: left;">61.6%</td>
<td style="text-align: left;">1.41</td>
</tr>
<tr class="even">
<td style="text-align: left;">scen5_sharpen_n5</td>
<td style="text-align: left;">Two-stage BB (t CI)</td>
<td style="text-align: left;">CTmax_1hr</td>
<td style="text-align: right;">1000</td>
<td style="text-align: left;">-0.623 (0.013)</td>
<td style="text-align: left;">0.753</td>
<td style="text-align: left;">86.3%</td>
<td style="text-align: left;">2.29</td>
</tr>
<tr class="odd">
<td style="text-align: left;">scen5_sharpen_n5</td>
<td style="text-align: left;">Joint 4PL (relative)</td>
<td style="text-align: left;">CTmax_1hr</td>
<td style="text-align: right;">1000</td>
<td style="text-align: left;">-0.005 (0.008)</td>
<td style="text-align: left;">0.252</td>
<td style="text-align: left;">95.2%</td>
<td style="text-align: left;">1.00</td>
</tr>
<tr class="even">
<td style="text-align: left;">scen5_sharpen_n5</td>
<td style="text-align: left;">Joint 4PL (absolute)</td>
<td style="text-align: left;">CTmax_1hr</td>
<td style="text-align: right;">1000</td>
<td style="text-align: left;">-0.012 (0.008)</td>
<td style="text-align: left;">0.245</td>
<td style="text-align: left;">94.9%</td>
<td style="text-align: left;">0.96</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-scen5" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-scen5-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="2026-05-16-two-stage-bias-sim-writeup_files/figure-html/fig-scen5-1.png" class="img-fluid figure-img" width="768">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-scen5-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5: Scenario 5 (varying k). Two-stage z biased high (+0.45 to +0.55), CTmax biased low (−0.44 to −0.62 °C); coverage on BB CTmax falls to 62% at <span class="math inline">\(n_{reps}=5\)</span>. Joint 4PL bias within MC SE on z; small positive CTmax bias (+0.03, +0.06); coverage holds at 93–95%.
</figcaption>
</figure>
</div>
</div>
</div>
<p><strong>Read.</strong> The prediction was wrong: <span class="math inline">\(k\)</span> varying with <span class="math inline">\(T\)</span> produces bias as large as Scenario 4. Two-stage <span class="math inline">\(z\)</span> biased high (+0.45 to +0.55) and CTmax biased low (−0.44 to −0.62 °C); Normal-CI BB CTmax coverage 62% at <span class="math inline">\(n_{\text{reps}}=5\)</span>.</p>
<p><strong>t-correction effect (CTmax)</strong>: BB 62% → 86%, bin 69% → 90% at <span class="math inline">\(n_{\text{reps}}=5\)</span> — same pattern as Scen 4: the t-fix helps but can’t reach nominal in the presence of structural bias. On z, the t-correction does reach nominal (95–96%).</p>
<p>Joint 4PL absorbs the <span class="math inline">\(k(T)\)</span> drift. The absolute extract again improves on the relative: CTmax bias +0.027 → −0.032 °C at <span class="math inline">\(n_{\text{reps}}=3\)</span>, +0.056 → −0.012 °C at <span class="math inline">\(n_{\text{reps}}=5\)</span>, both well within MC SE. Coverage 93–95% on both extracts.</p>
</section>
<section id="scenario-6-sweep-strength-of-u-drift" class="level1" data-number="8">
<h1 data-number="8"><span class="header-section-number">8</span> Scenario 6 — Sweep: strength of u drift</h1>
<p><strong>Question.</strong> How does the two-stage bias scale with the strength of the upper-asymptote drift? Is there a threshold of <span class="math inline">\(|\beta_u|\)</span> below which the bias is negligible in practice?</p>
<p><strong>Prediction.</strong> Bias monotonically increasing in <span class="math inline">\(|\beta_u|\)</span>; coverage correspondingly worse. Joint 4PL: bias within MC SE throughout.</p>
<p><strong>Design.</strong> Same shape as Scenario 3 but vary the upper-asymptote slope: <span class="math inline">\(\beta_u \in \{-0.005, -0.010, -0.015, -0.019\}\)</span> pp/°C. <span class="math inline">\(n_{\text{reps}} = 5\)</span>, <span class="math inline">\(N_{\text{sim}} = 1000\)</span> per cell. Four cells. True <span class="math inline">\(z\)</span> ranges 6.42–6.60; true <span class="math inline">\(CT_{\max,1\text{h}}\)</span> ranges 32.11–32.15.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-scen6" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-scen6-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="2026-05-16-two-stage-bias-sim-writeup_files/figure-html/fig-scen6-1.png" class="img-fluid figure-img" width="768">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-scen6-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6: Scenario 6 sweep over <span class="math inline">\(\beta_u\)</span> (strength of upper-asymptote drift). (a) Bias as a function of <span class="math inline">\(\beta_u\)</span>, with 95% MC-SE intervals; dashed line at zero. (b) Empirical 95% coverage; dashed line at nominal 0.95. Two-stage z bias <em>flips sign</em> between <span class="math inline">\(\beta_u=-0.005\)</span> and <span class="math inline">\(-0.010\)</span>. Two-stage CTmax bias is negative throughout but its absolute value <em>shrinks</em> as <span class="math inline">\(|\beta_u|\)</span> grows; coverage on the same axis <em>improves</em> (intervals widen with the misspecification). Joint 4PL holds bias and coverage near-constant across the sweep.
</figcaption>
</figure>
</div>
</div>
</div>
<p><strong>Read.</strong> The monotonicity prediction was partly wrong. Two-stage <span class="math inline">\(z\)</span> <strong>flips sign</strong> between <span class="math inline">\(\beta_u = -0.005\)</span> (positive bias of +0.16 to +0.19) and <span class="math inline">\(\beta_u = -0.010\)</span> (negative bias of −0.07 to −0.14), then becomes increasingly negative (−0.51 BB / −0.43 bin at the steepest cell). Two-stage CTmax bias stays negative throughout but its absolute magnitude <strong>shrinks</strong> as <span class="math inline">\(|\beta_u|\)</span> grows (−0.49 → −0.16 BB across the sweep). The t-correction lifts CTmax coverage to 88–97% across the sweep — closest to nominal at the steepest cell where Normal-CI bias is smallest. On z, t-correction reaches 95% at moderate <span class="math inline">\(|\beta_u|\)</span> but stalls at 78–84% for the steepest drift (BB) — bias too large to absorb.</p>
<p><strong>Joint 4PL holds coverage at 94–96% across the sweep</strong> on both extracts. <strong>The absolute extract systematically trims the z bias</strong> that the relative extract carries: at <span class="math inline">\(\beta_u = -0.019\)</span>, <code>joint_4pl</code> z bias +0.150 vs <code>joint_4pl_abs</code> −0.172 (the relative extract over-shoots positive when <code>up</code> drifts hard; the absolute extract over-shoots negative; truth is in between). CTmax bias is small for both extracts (+0.004 to +0.022 °C).</p>
</section>
<section id="scenario-7-sweep-level-of-upper-asymptote" class="level1" data-number="9">
<h1 data-number="9"><span class="header-section-number">9</span> Scenario 7 — Sweep: level of upper asymptote</h1>
<p><strong>Question.</strong> Sublethal endpoints (PSII signal, fertility, knockdown) rarely reach 1 even at <span class="math inline">\(T \to T_{\min}\)</span>. How does each estimator’s performance scale with the baseline level of <code>up</code>?</p>
<p><strong>Prediction.</strong> Two-stage <span class="math inline">\(z\)</span> bias should stay small (a constant asymptote bias across temperature cancels in the Stage-2 slope). <span class="math inline">\(CT_{\max,1\text{h}}\)</span> bias should grow as <span class="math inline">\(u_0\)</span> drops below 1 because the per-T midpoint estimates do not coincide with the absolute 50%-survival time when <code>up</code> is below 1. Joint 4PL: bias within MC SE throughout.</p>
<p><strong>Design.</strong> <code>up</code> constant in <span class="math inline">\(T\)</span> at <span class="math inline">\(u_0 \in \{0.65, 0.75, 0.85, 0.95, 0.99\}\)</span>; <code>low = 0.05</code>, <code>k = 8</code>, midpoint linear in <span class="math inline">\(T\)</span> with slope <span class="math inline">\(-0.15\)</span>. Beta-binomial likelihood (φ = 5). <span class="math inline">\(n_{\text{reps}} = 5\)</span>, <span class="math inline">\(N_{\text{sim}} = 1000\)</span> per cell. Five cells. True <span class="math inline">\(z = 6.667\)</span> (constant by construction); true <span class="math inline">\(CT_{\max,1\text{h}}\)</span> ranges 31.23 (at <span class="math inline">\(u_0=0.65\)</span>) to 32.22 (at <span class="math inline">\(u_0=0.99\)</span>).</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-scen7" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-scen7-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="2026-05-16-two-stage-bias-sim-writeup_files/figure-html/fig-scen7-1.png" class="img-fluid figure-img" width="768">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-scen7-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7: Scenario 7 sweep over <span class="math inline">\(u_0\)</span> (baseline upper asymptote). (a) Bias and (b) coverage as a function of <span class="math inline">\(u_0\)</span>. Two-stage <span class="math inline">\(CT_{\max,1h}\)</span> bias explodes from +0.26 °C at <span class="math inline">\(u_0=0.99\)</span> to −6.33 °C at <span class="math inline">\(u_0=0.65\)</span>, with coverage collapsing to 15%. Two-stage <span class="math inline">\(z\)</span> bias also grows, opposite to prediction. Joint 4PL coverage on <span class="math inline">\(z\)</span> stays at 94–95% across the sweep but its <span class="math inline">\(CT_{\max,1h}\)</span> bias also grows (+0.67 °C at <span class="math inline">\(u_0=0.65\)</span>); see open issues for the likely cause (relative vs absolute CTmax definition mismatch).
</figcaption>
</figure>
</div>
</div>
</div>
<p><strong>Read.</strong> Two-stage <span class="math inline">\(CT_{\max,1\text{h}}\)</span> <strong>catastrophically biased</strong> at low <span class="math inline">\(u_0\)</span>: −6.34 °C (BB) / −5.85 °C (bin) at <span class="math inline">\(u_0=0.65\)</span>, with Normal-CI coverage of 16% and 21% respectively. The t-correction lifts coverage to 58% (BB) / 63% (bin) but median CI widths balloon to 11.6 / 11.1 °C — wide enough to be operationally meaningless. <strong>The prediction that two-stage <span class="math inline">\(z\)</span> would stay near unbiased was wrong</strong>: <span class="math inline">\(z\)</span> bias grows to +3.09 (BB) at <span class="math inline">\(u_0=0.65\)</span> — when <code>up</code> is far from 1, the Stage-1 GLMs mis-estimate slopes asymmetrically across temperature, breaking the “constant bias cancels in the slope” argument.</p>
<p><strong>With the two-truth setup, the definition-mismatch artefact is gone.</strong> Each joint extract is now compared against the truth defined on its own threshold scale (see the “Two truths” paragraph in Common methods). After substitution:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th><span class="math inline">\(u_0\)</span></th>
<th>joint_4pl CTmax bias (rel)</th>
<th>coverage</th>
<th>joint_4pl_abs CTmax bias (abs)</th>
<th>coverage</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0.99</td>
<td>+0.047</td>
<td>94.3%</td>
<td>+0.028</td>
<td>94.3%</td>
</tr>
<tr class="even">
<td>0.95</td>
<td>+0.015</td>
<td>95.7%</td>
<td>+0.006</td>
<td>95.7%</td>
</tr>
<tr class="odd">
<td>0.85</td>
<td>−0.038</td>
<td>94.4%</td>
<td>−0.052</td>
<td>93.7%</td>
</tr>
<tr class="even">
<td>0.75</td>
<td>−0.119</td>
<td>94.2%</td>
<td>−0.176</td>
<td>92.9%</td>
</tr>
<tr class="odd">
<td>0.65</td>
<td>−0.240</td>
<td>92.5%</td>
<td>−0.355</td>
<td>92.5%</td>
</tr>
</tbody>
</table>
<p><strong>Both joint extracts are well-calibrated</strong> across the sweep on their own definition of CTmax. The residual negative bias at <span class="math inline">\(u_0 = 0.65\)</span> (−0.24 °C relative, −0.36 °C absolute) reflects genuine residual under-estimation of <code>up</code>/<code>k</code> in a constrained-geometry posterior, with 95% CrI coverage at 92.5% in both extracts — a small but real model deficiency, not a labelling artefact. Open issue 1 from the original writeup is closed.</p>
<p>z is essentially unaffected by extract choice (both joint variants within MC SE of zero with 94–95% coverage across the sweep), as expected — z derives from the slope of the line through whichever threshold is targeted, and the lines differ only in intercept, not slope, for this DGP family.</p>
<p>Convergence stress shows clearly at low <span class="math inline">\(u_0\)</span>: 194 sims with divergent transitions at <span class="math inline">\(u_0=0.65\)</span> (vs 3–18 at higher <span class="math inline">\(u_0\)</span>). Rhat pass dropped to 97.9%, ESS pass to 95.6% — chains still mostly OK but the boundary-constrained posterior is genuinely harder.</p>
</section>
<section id="scenario-8-sweep-design-intensity" class="level1" data-number="10">
<h1 data-number="10"><span class="header-section-number">10</span> Scenario 8 — Sweep: design intensity</h1>
<p><strong>Question.</strong> When does each estimator’s overhead pay off as the sampling design gets sparser and replication drops?</p>
<p><strong>Prediction.</strong> All methods: wider CIs as data sparsens. Joint 4PL has smallest inflation (information shared across temperature). Two-stage may fail or carry severe bias at the sparsest design.</p>
<p><strong>Design.</strong> Two grids: full (5 T × 6 durations × <span class="math inline">\(n_{\text{reps}}\)</span> cups) or sparse (3 T × 4 durations × <span class="math inline">\(n_{\text{reps}}\)</span> cups). Three <span class="math inline">\(n_{\text{reps}}\)</span> levels: <span class="math inline">\(\{1, 3, 5\}\)</span>. Six cells. DGP: <code>up = 0.92</code>, <code>low = 0.05</code>, <code>k = 8</code>, midpoint linear in <span class="math inline">\(T\)</span> with slope <span class="math inline">\(-0.15\)</span>, beta-binomial likelihood (φ = 5). True <span class="math inline">\(z = 6.667\)</span>, true <span class="math inline">\(CT_{\max,1\text{h}} = 32.088\,^\circ\text{C}\)</span>. <span class="math inline">\(N_{\text{sim}} = 1000\)</span> per cell.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-scen8" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-scen8-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="2026-05-16-two-stage-bias-sim-writeup_files/figure-html/fig-scen8-1.png" class="img-fluid figure-img" width="864">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-scen8-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;8: Scenario 8 sweep over design intensity. Six cells: sparse vs full grid × <span class="math inline">\(n_{reps} \in \{1, 3, 5\}\)</span>. (a) Bias by cell. (b) Coverage by cell. Two-stage at the sparsest cell (sparse <span class="math inline">\(\times\)</span> 1) gives nonsense (z RMSE &gt; 60); joint 4PL has wide intervals at the same cell but coverage of 99% on <span class="math inline">\(z\)</span> and 95% on <span class="math inline">\(CT_{\max,1h}\)</span>. Two-stage CTmax coverage stays below 70% even at the most generous (full × 5) cell.
</figcaption>
</figure>
</div>
</div>
</div>
<p><strong>Read.</strong> At sparse × 1 (12 cups, 1 replicate each), two-stage produces nonsense — z RMSE 19–45 (binomial / BB), CTmax RMSE 10–22. Joint 4PL returns wide but coherent intervals at the same cell (<span class="math inline">\(z\)</span> RMSE 2.15, CTmax RMSE 0.91; coverage 99% / 96%). At the most generous cell (full × 5), two-stage CTmax coverage is still 61% (BB Normal CI) — the design budget cannot rescue the architecture under partial mortality.</p>
<p><strong>Two distinct two-stage failure modes appear in this scenario.</strong> (i) <em>Full-design cells</em>: Normal-CI coverage degrades with <span class="math inline">\(n_{\text{reps}}\)</span> because tighter CIs around a non-shrinking bias miss truth more often (full × 1 = 87%, full × 5 = 61% on BB CTmax). The t-correction lifts this to 96% / 84% — useful at full × 1, partially useful at full × 5. (ii) <em>Sparse cells</em>: the t-correction at <span class="math inline">\(df = n_T - 2 = 1\)</span> uses <span class="math inline">\(t_{0.975, 1} = 12.71\)</span>, producing CI widths of 20–65 log10-units. These intervals are “calibrated” by mechanical inflation (sparse × 1 BB CTmax coverage 78% → 96%, width 6.4 → 41.6) but operationally meaningless.</p>
<p><strong>Joint 4PL coverage holds at 92–99% across all six cells</strong> with no mechanical CI inflation. Sparse-design cells incur the most chain stress: divergent transitions in 909 / 804 / 734 sims (out of 1000) at sparse × 1 / 3 / 5; Rhat pass rate drops to 95–98% but ESS and divergence-conditional inference remain viable.</p>
</section>
<section id="cross-cutting-summary" class="level1" data-number="11">
<h1 data-number="11"><span class="header-section-number">11</span> Cross-cutting summary</h1>
<div class="cell">
<div class="cell-output-display">
<div id="fig-summary" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-summary-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="2026-05-16-two-stage-bias-sim-writeup_files/figure-html/fig-summary-1.png" class="img-fluid figure-img" width="864">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-summary-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;9: Bias (top) and coverage (bottom) summaries for the five main scenarios at <span class="math inline">\(n_{reps}=5\)</span>. Each point shows mean bias / empirical coverage with MC-SE intervals; dashed reference lines at zero (bias) and 0.95 (coverage). Joint 4PL is within MC SE of zero on bias and at-or-above 0.93 on coverage in every scenario. Two-stage methods accumulate substantial bias and lose coverage as soon as the DGP departs from strict equivalence (Scenarios 3–5).
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="joint-4pl-convergence-across-scenarios" class="level1" data-number="12">
<h1 data-number="12"><span class="header-section-number">12</span> Joint 4PL convergence across scenarios</h1>
<div class="cell">
<div class="cell-output-display">
<div class="kable-table">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 21%">
<col style="width: 6%">
<col style="width: 10%">
<col style="width: 8%">
<col style="width: 10%">
<col style="width: 14%">
<col style="width: 16%">
<col style="width: 11%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Cell</th>
<th style="text-align: right;">n sims</th>
<th style="text-align: right;">n joint OK</th>
<th style="text-align: left;">R̂ pass %</th>
<th style="text-align: left;">ESS pass %</th>
<th style="text-align: left;">Diverg. pass %</th>
<th style="text-align: left;">Treedepth pass %</th>
<th style="text-align: left;">BFMI pass %</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">scen1_strict_eq_n3</td>
<td style="text-align: right;">1000</td>
<td style="text-align: right;">1000</td>
<td style="text-align: left;">100.0%</td>
<td style="text-align: left;">100.0%</td>
<td style="text-align: left;">100.0%</td>
<td style="text-align: left;">0.0%</td>
<td style="text-align: left;">100.0%</td>
</tr>
<tr class="even">
<td style="text-align: left;">scen1_strict_eq_n5</td>
<td style="text-align: right;">1000</td>
<td style="text-align: right;">1000</td>
<td style="text-align: left;">100.0%</td>
<td style="text-align: left;">100.0%</td>
<td style="text-align: left;">100.0%</td>
<td style="text-align: left;">0.0%</td>
<td style="text-align: left;">100.0%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">scen2_lik_misspec_n3</td>
<td style="text-align: right;">1000</td>
<td style="text-align: right;">1000</td>
<td style="text-align: left;">100.0%</td>
<td style="text-align: left;">100.0%</td>
<td style="text-align: left;">99.7%</td>
<td style="text-align: left;">0.0%</td>
<td style="text-align: left;">100.0%</td>
</tr>
<tr class="even">
<td style="text-align: left;">scen2_lik_misspec_n5</td>
<td style="text-align: right;">1000</td>
<td style="text-align: right;">1000</td>
<td style="text-align: left;">100.0%</td>
<td style="text-align: left;">100.0%</td>
<td style="text-align: left;">100.0%</td>
<td style="text-align: left;">0.0%</td>
<td style="text-align: left;">100.0%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">scen3_heat_lowers_u_n3</td>
<td style="text-align: right;">1000</td>
<td style="text-align: right;">1000</td>
<td style="text-align: left;">100.0%</td>
<td style="text-align: left;">99.7%</td>
<td style="text-align: left;">91.1%</td>
<td style="text-align: left;">0.0%</td>
<td style="text-align: left;">100.0%</td>
</tr>
<tr class="even">
<td style="text-align: left;">scen3_heat_lowers_u_n5</td>
<td style="text-align: right;">1000</td>
<td style="text-align: right;">1000</td>
<td style="text-align: left;">99.9%</td>
<td style="text-align: left;">99.9%</td>
<td style="text-align: left;">98.2%</td>
<td style="text-align: left;">0.0%</td>
<td style="text-align: left;">100.0%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">scen4_compress_n3</td>
<td style="text-align: right;">1000</td>
<td style="text-align: right;">1000</td>
<td style="text-align: left;">99.7%</td>
<td style="text-align: left;">99.9%</td>
<td style="text-align: left;">91.9%</td>
<td style="text-align: left;">0.0%</td>
<td style="text-align: left;">100.0%</td>
</tr>
<tr class="even">
<td style="text-align: left;">scen4_compress_n5</td>
<td style="text-align: right;">1000</td>
<td style="text-align: right;">1000</td>
<td style="text-align: left;">100.0%</td>
<td style="text-align: left;">99.7%</td>
<td style="text-align: left;">98.7%</td>
<td style="text-align: left;">0.0%</td>
<td style="text-align: left;">100.0%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">scen5_sharpen_n3</td>
<td style="text-align: right;">1000</td>
<td style="text-align: right;">1000</td>
<td style="text-align: left;">99.7%</td>
<td style="text-align: left;">99.7%</td>
<td style="text-align: left;">91.1%</td>
<td style="text-align: left;">0.0%</td>
<td style="text-align: left;">100.0%</td>
</tr>
<tr class="even">
<td style="text-align: left;">scen5_sharpen_n5</td>
<td style="text-align: right;">1000</td>
<td style="text-align: right;">1000</td>
<td style="text-align: left;">99.9%</td>
<td style="text-align: left;">100.0%</td>
<td style="text-align: left;">98.1%</td>
<td style="text-align: left;">0.0%</td>
<td style="text-align: left;">100.0%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">scen6_ub_m005</td>
<td style="text-align: right;">1000</td>
<td style="text-align: right;">1000</td>
<td style="text-align: left;">99.9%</td>
<td style="text-align: left;">99.9%</td>
<td style="text-align: left;">98.1%</td>
<td style="text-align: left;">0.0%</td>
<td style="text-align: left;">100.0%</td>
</tr>
<tr class="even">
<td style="text-align: left;">scen6_ub_m010</td>
<td style="text-align: right;">1000</td>
<td style="text-align: right;">1000</td>
<td style="text-align: left;">99.9%</td>
<td style="text-align: left;">99.9%</td>
<td style="text-align: left;">98.2%</td>
<td style="text-align: left;">0.0%</td>
<td style="text-align: left;">100.0%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">scen6_ub_m015</td>
<td style="text-align: right;">1000</td>
<td style="text-align: right;">1000</td>
<td style="text-align: left;">99.9%</td>
<td style="text-align: left;">100.0%</td>
<td style="text-align: left;">98.7%</td>
<td style="text-align: left;">0.0%</td>
<td style="text-align: left;">100.0%</td>
</tr>
<tr class="even">
<td style="text-align: left;">scen6_ub_m019</td>
<td style="text-align: right;">1000</td>
<td style="text-align: right;">1000</td>
<td style="text-align: left;">100.0%</td>
<td style="text-align: left;">99.8%</td>
<td style="text-align: left;">99.2%</td>
<td style="text-align: left;">0.0%</td>
<td style="text-align: left;">100.0%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">scen7_u0_065</td>
<td style="text-align: right;">1000</td>
<td style="text-align: right;">1000</td>
<td style="text-align: left;">97.9%</td>
<td style="text-align: left;">95.6%</td>
<td style="text-align: left;">80.6%</td>
<td style="text-align: left;">0.0%</td>
<td style="text-align: left;">100.0%</td>
</tr>
<tr class="even">
<td style="text-align: left;">scen7_u0_075</td>
<td style="text-align: right;">1000</td>
<td style="text-align: right;">1000</td>
<td style="text-align: left;">99.7%</td>
<td style="text-align: left;">99.0%</td>
<td style="text-align: left;">87.6%</td>
<td style="text-align: left;">0.0%</td>
<td style="text-align: left;">100.0%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">scen7_u0_085</td>
<td style="text-align: right;">1000</td>
<td style="text-align: right;">1000</td>
<td style="text-align: left;">99.9%</td>
<td style="text-align: left;">99.5%</td>
<td style="text-align: left;">94.9%</td>
<td style="text-align: left;">0.0%</td>
<td style="text-align: left;">100.0%</td>
</tr>
<tr class="even">
<td style="text-align: left;">scen7_u0_095</td>
<td style="text-align: right;">1000</td>
<td style="text-align: right;">1000</td>
<td style="text-align: left;">100.0%</td>
<td style="text-align: left;">100.0%</td>
<td style="text-align: left;">99.0%</td>
<td style="text-align: left;">0.0%</td>
<td style="text-align: left;">100.0%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">scen7_u0_099</td>
<td style="text-align: right;">1000</td>
<td style="text-align: right;">1000</td>
<td style="text-align: left;">99.9%</td>
<td style="text-align: left;">99.9%</td>
<td style="text-align: left;">99.7%</td>
<td style="text-align: left;">0.0%</td>
<td style="text-align: left;">100.0%</td>
</tr>
<tr class="even">
<td style="text-align: left;">scen8_full_n1</td>
<td style="text-align: right;">1000</td>
<td style="text-align: right;">1000</td>
<td style="text-align: left;">98.8%</td>
<td style="text-align: left;">98.7%</td>
<td style="text-align: left;">57.0%</td>
<td style="text-align: left;">0.0%</td>
<td style="text-align: left;">100.0%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">scen8_full_n3</td>
<td style="text-align: right;">1000</td>
<td style="text-align: right;">1000</td>
<td style="text-align: left;">99.9%</td>
<td style="text-align: left;">99.8%</td>
<td style="text-align: left;">92.0%</td>
<td style="text-align: left;">0.0%</td>
<td style="text-align: left;">100.0%</td>
</tr>
<tr class="even">
<td style="text-align: left;">scen8_full_n5</td>
<td style="text-align: right;">1000</td>
<td style="text-align: right;">1000</td>
<td style="text-align: left;">100.0%</td>
<td style="text-align: left;">100.0%</td>
<td style="text-align: left;">98.2%</td>
<td style="text-align: left;">0.0%</td>
<td style="text-align: left;">100.0%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">scen8_sparse_n1</td>
<td style="text-align: right;">1000</td>
<td style="text-align: right;">1000</td>
<td style="text-align: left;">97.6%</td>
<td style="text-align: left;">94.6%</td>
<td style="text-align: left;">9.1%</td>
<td style="text-align: left;">0.0%</td>
<td style="text-align: left;">100.0%</td>
</tr>
<tr class="even">
<td style="text-align: left;">scen8_sparse_n3</td>
<td style="text-align: right;">1000</td>
<td style="text-align: right;">1000</td>
<td style="text-align: left;">97.5%</td>
<td style="text-align: left;">94.3%</td>
<td style="text-align: left;">19.6%</td>
<td style="text-align: left;">0.0%</td>
<td style="text-align: left;">100.0%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">scen8_sparse_n5</td>
<td style="text-align: right;">1000</td>
<td style="text-align: right;">1000</td>
<td style="text-align: left;">95.4%</td>
<td style="text-align: left;">91.0%</td>
<td style="text-align: left;">26.6%</td>
<td style="text-align: left;">0.0%</td>
<td style="text-align: left;">100.0%</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>R̂ and ESS pass rates are above 95% in every cell. <strong>Divergent transitions</strong> are the main convergence flag: rare in Scenarios 1–6 (typically ≤ 100 sims out of 1000) but climb sharply at the harder posterior geometries — 194 sims at Scen 7 <span class="math inline">\(u_0 = 0.65\)</span>, and 430–909 sims across the Scen 8 sparse cells. Coverage on the bias / coverage table still holds at near-nominal for the joint 4PL throughout, but the “bias conditional on full convergence” check (open issue 3 below) remains the right follow-up. <strong>Treedepth saturation</strong> persists on essentially every fit at <code>max_treedepth = 16</code> (was 12 in the earlier pass) — the chain explores fully via long trajectories but the ceiling flag itself isn’t masking poor calibration.</p>
</section>
<section id="open-issues" class="level1" data-number="13">
<h1 data-number="13"><span class="header-section-number">13</span> Open issues</h1>
<ol type="1">
<li><p><strong><del>Definition mismatch on joint-4PL CTmax</del></strong> — <strong>RESOLVED</strong> in two passes:</p>
<ul>
<li><strong>2026-05-19 rebuild (estimator side):</strong> every joint fit now reports both <code>target_surv = "relative"</code> (the package default) and <code>target_surv = "absolute"</code> extracts.</li>
<li><strong>2026-05-19 aggregation side (in this writeup):</strong> each joint extract is now compared against its own truth, not the single absolute truth that the driver writes into every row. Relative truth is computed from <code>mid(T) = log10(60)</code> (intercept and slope from the DGP); absolute truth is the per-cell value already in the per-sim files.</li>
</ul>
<p>After both fixes, the joint 4PL is well-calibrated on its own definition of CTmax across the Scenario 7 sweep (coverage 92.5–96% on both extracts; residual bias −0.24 / −0.36 °C only at the extreme <span class="math inline">\(u_0 = 0.65\)</span> cell). <strong>The original ~+0.675 °C “bias” was 95 % labelling, ~5 % residual model error.</strong> The recommendation for the manuscript: <strong>report the extract matching the inferential target</strong> — relative for “depletion of the vulnerable fraction” interpretation, absolute for the classical “50% literal” interpretation that two-stage methods target — and compare against the truth on the same scale.</p></li>
<li><p><strong><del>Treedepth saturation</del></strong> — <strong>partially resolved</strong>. At <code>max_treedepth = 16</code> (was 12), the ceiling still saturates on essentially every fit, but the calibration in this rebuild is at-or-near nominal across 22 of 25 cells (the three exceptions are Scen 7 <span class="math inline">\(u_0 \in \{0.65, 0.75, 0.85\}\)</span> on the relative extract, which is resolved by switching to the absolute extract — see issue 1). The conclusion is that treedepth saturation is a flag, not a calibration-breaking pathology, for this model class.</p></li>
<li><p><strong>Bias conditional on full convergence.</strong> The headline summaries are computed on all fits, including those with divergent transitions. The 2026-05-19 rebuild has divergence-heavy cells at Scen 7 (194 sims with divergences at <span class="math inline">\(u_0 = 0.65\)</span>) and Scen 8 sparse (430–909 sims at <span class="math inline">\(n_{\text{reps}} \in \{1, 3, 5\}\)</span>). The same summaries restricted to “all-pass” fits have not been computed yet; checking whether the residual joint-4PL CTmax bias at <span class="math inline">\(u_0 = 0.65\)</span> (−0.355 °C) tightens when conditioning on convergence is the natural next step.</p></li>
<li><p><strong>The t-correction is a substantial coverage fix in some regimes, not in others.</strong> Across Scenarios 1–2 (correctly-specified mean structure) and Scenario 6 at modest <span class="math inline">\(|\beta_u|\)</span>, the t-quantile delta-method CI lifts two-stage coverage from 82–88% (Normal) to 93–97% — a clean small-sample correction that closes the gap. Under structural shape misspecification (Scenarios 3–5 and Scenarios 7–8 at high bias), the t-correction widens CIs but can’t catch <span class="math inline">\(\geq\)</span> 0.5 °C CTmax bias; coverage stalls at 60–85%. The t-correction should be the <em>default</em> CI method in any future two-stage TDT workflow — it is a strict improvement over the Normal-quantile CI when bias is small, and it is no worse when bias is large.</p></li>
<li><p><strong>Patched (BB) two-stage was <em>not</em> a patch.</strong> Across Scenarios 2–5, the BB-Stage-1 variant performs <em>worse</em> on coverage than the binomial-Stage-1 variant, contradicting the prediction that correcting the likelihood would help. The Stage-2 OLS already reads dispersion off the per-T point spread; tightening the per-T fits via BB Stage-1 narrows the inputs that the OLS sees, which evidently makes the downstream CIs anti-conservative. The conclusion is that the BB Stage-1 + Normal CI combination should <em>not</em> be recommended.</p></li>
<li><p><strong>Prior sensitivity</strong> of the joint 4PL has not been varied. A small persistent positive z bias (+0.06 to +0.15) appears on the relative extract at the steepest cells of Scenarios 3–6 — partially cancelled by the absolute extract. Worth a small prior-sensitivity sweep on <code>mid_T_slope</code> to confirm.</p></li>
<li><p><strong><del>Beta-binomial Stage-1 outlier fits</del></strong> — <strong>RESOLVED (2026-05-19).</strong> Pathological BB Stage-1 fits that passed the driver’s success check but produced wildly biased Stage-2 estimates (z bias up to 849 °C; CTmax bias up to 433 °C) are now screened out at the writeup level (|z bias| &gt; 20 °C OR |CTmax bias| &gt; 10 °C — see “BB Stage-1 pathology screening” in the Common methods section). 153 / 25,000 sims affected across all cells (0.6 %). After screening, BB RMSE on <span class="math inline">\(z\)</span> at Scenario 1 <span class="math inline">\(n_{\text{reps}}=5\)</span> drops from 3.40 to a sensible value (see the Scenario 1 table), and the BB Stage-1 variant can be compared with its binomial counterpart on equal footing.</p></li>
</ol>
</section>
<section id="bottom-line" class="level1" data-number="14">
<h1 data-number="14"><span class="header-section-number">14</span> Bottom line</h1>
<ul>
<li><strong>Strict equivalence (Scenario 1)</strong>: all six estimators unbiased. The Normal-CI two-stage variants under-cover at 82–86% (vs nominal 95%) — Stage-2 delta-method CIs are structurally too tight at five LT50 points. <strong>The t-quantile small-sample correction closes the gap (93–97%)</strong> — it is a strict improvement and should be the default CI method in any two-stage workflow. Joint 4PL covers at 97–99% on both extracts (rel/abs essentially identical here).</li>
<li><strong>Overdispersion alone (Scenario 2)</strong>: same pattern. Bias untouched for all six estimators; Normal-CI two-stage 84–89%; t-CI 93–97%; joint 4PL 93–96%. Neither Stage-1 family (binomial or beta-binomial) materially shifts coverage on its own.</li>
<li><strong>Structural drift in asymptotes or slope (Scenarios 3–5)</strong>: two-stage biases of 0.27–0.62 °C on <span class="math inline">\(CT_{\max,1\text{h}}\)</span> and 0.08–0.56 on <span class="math inline">\(z\)</span>, <strong>insensitive to replication</strong>. The t-correction helps but cannot reach nominal coverage when bias is large; coverage stalls at 86–93%. <strong>Joint 4PL with the absolute extract is near-unbiased</strong> on CTmax (≤ 0.05 °C across all three scenarios) with coverage 93–96%.</li>
<li><strong>Scaling with misspecification magnitude (Scenario 6)</strong>: two-stage z bias flips sign across the <span class="math inline">\(\beta_u\)</span> sweep; absolute magnitude of CTmax bias shrinks as <span class="math inline">\(|\beta_u|\)</span> grows (CI widths grow faster). Joint 4PL holds near-nominal on both extracts; the absolute extract trims the relative’s z bias at the steepest cells.</li>
<li><strong>Scenario 7 (sublethal-relevant: partial maximum survival at all T)</strong>: two-stage <span class="math inline">\(CT_{\max,1\text{h}}\)</span> catastrophically biased — up to −6.3 °C with coverage 16% at <span class="math inline">\(u_0 = 0.65\)</span>. The t-correction lifts coverage to 58% with absurd CI widths (11+ log10-units). <strong>Both joint 4PL extracts (relative and absolute), each compared against its own definition of CTmax, hold coverage at 92.5–95.7% across the entire sweep</strong> with bias within MC SE except for a small residual at the extreme <span class="math inline">\(u_0 = 0.65\)</span> cell (−0.24 °C / −0.36 °C). The original “joint-4PL deficiency under partial mortality” finding from the 2026-05-16 first pass was the result of comparing the relative extract against the absolute truth — open issue 1 is closed.</li>
<li><strong>Sparse design × low replication (Scenario 8 sparse × 1)</strong>: two-stage produces estimates with no operational meaning (RMSE 22 on CTmax, 45 on z). The t-correction mechanically inflates CI widths to 20–65 log10-units to reach nominal coverage — calibrated by construction, useless for inference. <strong>Joint 4PL returns intervals of appropriate width</strong> (CTmax RMSE 0.91, z RMSE 2.15; coverage 95% / 99%) — wide because the data is wide, not artificially so.</li>
</ul>
<p>Two clean <strong>manuscript-ready recommendations</strong> emerge:</p>
<ol type="1">
<li>The <strong>joint 4PL with the absolute-CTmax extract</strong> is well-calibrated across all 25 simulation cells, including the regimes where the two-stage fails (partial mortality at all T, sparse design × low replication).</li>
<li>If the two-stage architecture is retained for any reason, the <strong>t-quantile small-sample CI correction is a strict improvement</strong> over the Normal-quantile default and should be the recommended reporting standard. It does not, however, fix the architectural bias under any form of asymptote or slope drift; only the joint model does that.</li>
</ol>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>